import { Product, NetworkEvent } from "./schema";

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Bastar Dhokra (Hero Scenario Artisan: Shanti Devi)
  {
    id: "prod-dokra-01",
    artisan_id: "artisan-shanti-devi",
    title: "Bastar Dhokra Bell Metal Nandi Bull Tribal Figurine",
    title_hi: "बस्तर ढोकरा घंटी धातु नंदी बैल पारंपरिक प्रतिमा",
    description: "Ancient non-ferrous lost-wax bell metal figurine handcrafted by indigenous artisans in Kondagaon, Bastar. Characterized by delicate twisted wax wire detailing, ritual horns, and hollow brass metallurgy.",
    description_hi: "कोंडागांव, बस्तर के पारंपरिक कारीगरों द्वारा लॉस्ट-वैक्स (मोम ढलाई) विधि से निर्मित पीतल और घंटी धातु की दुर्लभ नंदी बैल मूर्ति।",
    category: "metalwork",
    craft_name: "Bastar Dhokra",
    state: "Chhattisgarh",
    district: "Bastar",
    materials: ["Brass Scrap Alloy", "Bell Metal", "Natural Beeswax", "Termite Mound Clay", "River Silt"],
    motifs: ["Spiraled Wax Filigree", "Tribal Sun Eyes", "Ceremonial Bell Collar", "Sacred Horns"],
    dimensions: { length: 18, width: 10, height: 16, unit: "cm" },
    inventory: 3,
    suggested_min_price: 3600,
    suggested_max_price: 4100,
    final_price: 3900,
    price_analysis: {
      id: "pa-dokra-01",
      product_id: "prod-dokra-01",
      comparable_count: 8,
      min_price: 3499,
      median_price: 3775,
      max_price: 4299,
      recommended_min: 3600,
      recommended_max: 4100,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 8 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
        {
          id: "comp-dok-1",
          product_id: "prod-dokra-01",
          market_price_observation_id: "obs-dok-1",
          title: "Tribal Bastar Dhokra Bell Metal Nandi Bull Handcrafted Figurine (18 cm)",
          marketplace: "Amazon",
          price: 3799,
          currency: "INR",
          url: "https://www.amazon.in/dp/B09DOKRA01",
          similarity_score: 0.96,
          craft_similarity: 0.98,
          category_similarity: 0.95,
          material_similarity: 0.94,
          technique_similarity: 0.96,
          size_similarity: 0.95,
          handmade_status: true,
          match_reasons: ["Identical heritage craft lineage (Bastar Dhokra)", "Lost-wax casting technique match", "Proportional dimension alignment"],
          retrieved_at: "2026-09-11T18:30:00.000Z",
          source_type: "demo_data",
          is_demo: true,
        },
        {
          id: "comp-dok-2",
          product_id: "prod-dokra-01",
          market_price_observation_id: "obs-dok-2",
          title: "Bastar Tribal Art Brass Bell Metal Sacred Nandi Bull Sculpture",
          marketplace: "Flipkart",
          price: 3499,
          currency: "INR",
          url: "https://www.flipkart.com/item/FLPDOKRA02",
          similarity_score: 0.93,
          craft_similarity: 0.95,
          category_similarity: 0.92,
          material_similarity: 0.90,
          technique_similarity: 0.92,
          size_similarity: 0.88,
          handmade_status: true,
          match_reasons: ["Craft cluster match (Bastar Dhokra)", "Bell metal alloy concordance"],
          retrieved_at: "2026-09-11T18:30:00.000Z",
          source_type: "demo_data",
          is_demo: true,
        },
        {
          id: "comp-dok-3",
          product_id: "prod-dokra-01",
          market_price_observation_id: "obs-dok-3",
          title: "Authentic Bastar Bell Metal Nandi Totem - Kondagaon Craft Guild",
          marketplace: "ONDC (TribesIndia)",
          price: 4100,
          currency: "INR",
          url: "https://tribesindia.ondc.org/item/TI-DOK-33",
          similarity_score: 0.97,
          craft_similarity: 0.98,
          category_similarity: 0.96,
          material_similarity: 0.97,
          technique_similarity: 0.98,
          size_similarity: 0.94,
          handmade_status: true,
          match_reasons: ["Kondagaon artisan guild certified", "Cire-perdue non-ferrous hollow casting"],
          retrieved_at: "2026-09-11T18:30:00.000Z",
          source_type: "demo_data",
          is_demo: true,
        },
        {
          id: "comp-dok-4",
          product_id: "prod-dokra-01",
          market_price_observation_id: "obs-dok-4",
          title: "Chhatisgarh Indigenous Dhokra Bull Metal Art Piece",
          marketplace: "ONDC (CraftsBazaar)",
          price: 3650,
          currency: "INR",
          url: "https://craftsbazaar.ondc.org/p/cb-7712",
          similarity_score: 0.91,
          craft_similarity: 0.94,
          category_similarity: 0.90,
          material_similarity: 0.88,
          technique_similarity: 0.90,
          size_similarity: 0.90,
          handmade_status: true,
          match_reasons: ["Regional artisan cooperative listing", "Pure lost-wax casting"],
          retrieved_at: "2026-09-11T18:30:00.000Z",
          source_type: "demo_data",
          is_demo: true,
        },
      ],
    },
    artisan_price_decision: {
      product_id: "prod-dokra-01",
      recommended_min: 3600,
      recommended_max: 4100,
      final_price: 3900,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    cost_reference: {
      material_cost: 850,
      labor_hours: 22,
      craft_complexity: "High",
      hourly_benchmark: 140,
      estimated_cost_subtotal: 3080,
      reference_min: 3500,
      reference_max: 4500,
      benchmark_source: "Chhattisgarh Tribal Artisan Guild Reference",
      rationale: "Optional internal cost breakdown: Material ₹850 + 22 hrs @ ₹140/hr. Kept separate from external market price discovery.",
      is_optional_reference: true,
    },
    pricing_breakdown: {
      material_cost: 850,
      labor_hours: 22,
      craft_complexity: "High",
      hourly_benchmark: 140,
      fair_wage_subtotal: 3080,
      suggested_min_price: 3600,
      suggested_max_price: 4100,
      ondc_export_markup_suggestion: 5100,
      benchmark_source: "Chhattisgarh Tribal Artisan Guild Guideline",
      rationale: "Market Analysis: 8 comparable products found across approved sources (Amazon, Flipkart, ONDC). Recommended range ₹3,600 – ₹4,100. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/bastar-dhokra.jpg",
    additional_images: [
      "/crafts/bastar-dhokra.jpg"
    ],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null, // No fake government identifier
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Bastar Bell Metal Handicrafts",
    artisan_story: "Our family in Kondagaon has practiced this unbroken 4,000-year-old Indus Valley metallurgy across 5 generations. The single-use clay mold is broken open to reveal the metal sculpture, making every single creation irreplaceable.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Bastar Dhokra",
      region: "Bastar, Chhattisgarh",
      detected_materials: ["Bell metal alloy", "Natural beeswax", "Termite refractory clay"],
      detected_motifs: ["Spiraled wax filigree", "Tribal animal morphology", "Nandi bull profile"],
      language_detected: "Hindi",
      confidence_score: 0.96,
      speech_keywords: ["ढोकरा", "घंटी धातु", "मोम ढलाई", "बस्तर", "नंदी बैल", "पीतल"],
      visual_features: ["Twisted wax filigree pattern", "Hollow core bronze casting", "Tribal horned bovine silhouette"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered Bastar Dhokra craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-dokra-01",
      product_id: "prod-dokra-01",
      craft_name: "Bastar Dhokra",
      region: "Kondagaon, Bastar",
      state: "Chhattisgarh",
      district: "Bastar",
      artisan_name: "Shanti Devi & Budhram Baghel",
      artisan_lineage: "Ghadwa tribal brass-casters lineage (5th Generation)",
      traditional_technique: "Cire-Perdue (Lost Wax) Indigenous Metallurgy: Clay core shaped from termite soil, wound with hand-drawn beeswax threads, encased in refractory mud, and poured with liquid scrap bell metal in an open hearth.",
      materials: ["Scrap Brass", "Bell Metal", "Bee Wax", "Termite Mound Clay"],
      motifs: ["Twisted wax filigree", "Tribal Sun Eyes", "Ceremonial Neck Bells"],
      cultural_story: "Direct continuum with the iconic 'Dancing Girl of Mohenjo-Daro' bronze (c. 2300 BCE). For the tribal communities of Bastar, Dhokra sculptures serve as ritual protectors and totems.",
      artisan_story: "We gather beeswax from local sal forests and river clay from the Indravati riverbanks. The mold must be broken to birth the artifact.",
      original_language: "Hindi / Gondi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "high",
      sources: [
        { title: "Bastar Tribal Craft Guild Documentation", type: "Guild Archive", is_demo: true },
        { title: "National Crafts Council India - Lost Wax Register", type: "Government Heritage Record", is_demo: true }
      ],
      claims: [
        {
          id: "c-dokra-1",
          claim_text: "Single-mold lost wax casting with no mechanical joints or identical duplicates.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan spoken declaration & workshop process review",
          is_demo_reference: true,
        },
        {
          id: "c-dokra-2",
          claim_text: "Recognized as indigenous Bastar Dhokra handicraft under GI Registry documentation.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — GI Registry (craft-level registration verified)",
          is_demo_reference: true,
        },
        {
          id: "c-dokra-3",
          claim_text: "Beeswax winding density indicates Grade-A master Ghadwa lineage technique.",
          source_type: "ai",
          provenance_label: "AI Suggested",
          verification_status: "requires_verification",
          source_reference: "AI surface geometry measurement — requires guild verification",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-01T10:00:00.000Z",
      updated_at: "2026-09-05T14:30:00.000Z",
    },
    created_at: "2026-09-01T10:00:00.000Z",
    updated_at: "2026-09-05T14:30:00.000Z",
    image_attribution: {
      image_url: "/crafts/bastar-dhokra.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Dhokra_item_Raodeo.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo by Saiphani02, via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 2. Jaipur Blue Pottery
  {
    id: "prod-blue-pottery-02",
    artisan_id: "artisan-ramesh-kripal",
    title: "Handcrafted Jaipur Blue Pottery Floral Motif Vase",
    title_hi: "हस्तनिर्मित जयपुर ब्लू पॉटरी फ्लोरल फूलदान",
    description: "Unique low-fire ceramic vase crafted without clay using powdered quartz stone, cullet glass, multani mitti, and natural plant gums. Hand-painted with Persian cobalt blue and turquoise floral arabesques.",
    description_hi: "पारंपरिक जयपुर तकनीक से बिना मिट्टी के क्वार्ट्ज़ और मुल्तानी मिट्टी से निर्मित फूलदान, जिस पर कोबाल्ट नीले और फिरोज़ी रंगों से पारंपरिक बेल-बूटे उकेरे गए हैं।",
    category: "pottery",
    craft_name: "Jaipur Blue Pottery",
    state: "Rajasthan",
    district: "Jaipur",
    materials: ["Ground Quartz Stone", "Cullet Glass", "Multani Mitti", "Natural Borax", "Cobalt Oxide Pigment"],
    motifs: ["Persian Floral Arabesque", "Lotus Rosette", "Geometrical Neck Bands"],
    dimensions: { length: 15, width: 15, height: 28, unit: "cm" },
    inventory: 5,
    suggested_min_price: 1600,
    suggested_max_price: 2200,
    final_price: 1850,

    price_analysis: {
      id: "pa-blue-pottery-02",
      product_id: "prod-blue-pottery-02",
      comparable_count: 6,
      min_price: 1699,
      median_price: 1850,
      max_price: 2250,
      recommended_min: 1600,
      recommended_max: 2200,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 6 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC Rajasthan).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-jbp-1",
                  "product_id": "prod-blue-pottery-02",
                  "market_price_observation_id": "obs-jbp-1",
                  "title": "Handmade Jaipur Blue Pottery Flower Vase 10 inch Persian Floral",
                  "marketplace": "Amazon",
                  "price": 1850,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08JBP01",
                  "similarity_score": 0.95,
                  "craft_similarity": 0.97,
                  "category_similarity": 0.95,
                  "material_similarity": 0.94,
                  "technique_similarity": 0.95,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Jaipur Blue Pottery craft family",
                          "Quartz-based non-clay body",
                          "Persian floral motif alignment"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-jbp-2",
                  "product_id": "prod-blue-pottery-02",
                  "market_price_observation_id": "obs-jbp-2",
                  "title": "Authentic Rajasthan Blue Pottery Hand Painted Table Vase",
                  "marketplace": "Flipkart",
                  "price": 1699,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPJBP02",
                  "similarity_score": 0.92,
                  "craft_similarity": 0.95,
                  "category_similarity": 0.92,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Regional artisan cooperative listing",
                          "Hand-painted cobalt glaze"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-jbp-3",
                  "product_id": "prod-blue-pottery-02",
                  "market_price_observation_id": "obs-jbp-3",
                  "title": "Kripal Kumbh Style Cobalt Blue Pottery Decorative Vase",
                  "marketplace": "ONDC (RajasthanCrafts)",
                  "price": 2100,
                  "currency": "INR",
                  "url": "https://rajasthan.ondc.org/p/rj-pot-101",
                  "similarity_score": 0.96,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.95,
                  "material_similarity": 0.96,
                  "technique_similarity": 0.97,
                  "size_similarity": 0.94,
                  "handmade_status": true,
                  "match_reasons": [
                          "Kripal Kumbh master lineage style",
                          "Natural oxide pigment formulation"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-jbp-4",
                  "product_id": "prod-blue-pottery-02",
                  "market_price_observation_id": "obs-jbp-4",
                  "title": "Heritage Living Vault Jaipur Glazed Quartz Pottery Vase",
                  "marketplace": "Approved Partner",
                  "price": 2250,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/jbp-2250",
                  "similarity_score": 0.9,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.9,
                  "material_similarity": 0.88,
                  "technique_similarity": 0.9,
                  "size_similarity": 0.89,
                  "handmade_status": true,
                  "match_reasons": [
                          "Verified master craftsman workshop",
                          "Single kiln firing process"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-blue-pottery-02",
      recommended_min: 1600,
      recommended_max: 2200,
      final_price: 1850,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 380,
      labor_hours: 11,
      craft_complexity: "Medium",
      hourly_benchmark: 135,
      fair_wage_subtotal: 1485,
      suggested_min_price: 1600,
      suggested_max_price: 2200,
      ondc_export_markup_suggestion: 2450,
      benchmark_source: "Rajasthan State Handloom & Handicrafts Benchmark",
      rationale: "Material Cost ₹380 + Estimated Labour (11 hrs @ ₹135/hr benchmark = ₹1,485). Suggested range ₹1,600 – ₹2,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/jaipur-blue-pottery.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Jaipur Ceramic Arts",
    artisan_story: "My family has practiced this delicate craft in Kot Jewar under the patronage of Jaipur master traditions. Every piece is shaped on the mold by hand and fired in a single wood-kiln cycle.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Jaipur Blue Pottery",
      region: "Jaipur, Rajasthan",
      detected_materials: ["Quartz stone powder", "Glass frit", "Cobalt oxide"],
      detected_motifs: ["Persian arabesque", "Foliage scrolls"],
      language_detected: "Hindi",
      confidence_score: 0.94,
      speech_keywords: ["ब्लू पॉटरी", "क्वार्ट्ज़", "मुल्तानी मिट्टी", "कोबाल्ट नीला", "बिना मिट्टी"],
      visual_features: ["Cobalt blue glaze gloss", "Turquoise botanical infill", "Semi-porous non-thrown body"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-blue-pottery-02",
      product_id: "prod-blue-pottery-02",
      craft_name: "Jaipur Blue Pottery",
      region: "Kot Jewar, Jaipur",
      state: "Rajasthan",
      district: "Jaipur",
      artisan_name: "Ramesh Kripal",
      artisan_lineage: "Kot Jewar Pottery Guild (Kripal Kumbh disciples)",
      traditional_technique: "Clay-free Egyptian faience-derived ceramic: Quartz powder mixed with saji, katira gond, and glass, pressed in open plaster moulds, painted freehand with metal oxides, and single-fired at 800°C.",
      materials: ["Quartz Powder", "Cullet Glass", "Katira Gond", "Cobalt Oxide"],
      motifs: ["Persian Floral Arabesque", "Foliage Scrolls", "Geometrical Borders"],
      cultural_story: "Introduced to Jaipur by Maharaja Sawai Ram Singh II in the 19th century after seeing kite-flying glazed cords. Renowned for its radiant turquoise hues and imperviousness to cracking.",
      artisan_story: "We do not touch river clay. The quartz is ground into white flour and mixed with natural gum resin.",
      original_language: "Hindi / Rajasthani",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "medium",
      sources: [
        { title: "Jaipur Blue Pottery Guild Archives", type: "Regional Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-bp-1",
          claim_text: "100% clay-free composition formulated exclusively from Rajasthan mineral quartz.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan declaration & kiln record",
          is_demo_reference: true,
        },
        {
          id: "c-bp-2",
          claim_text: "Geographical Indication recognized craft of Jaipur district.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-03T11:20:00.000Z",
      updated_at: "2026-09-08T16:00:00.000Z",
    },
    created_at: "2026-09-03T11:20:00.000Z",
    updated_at: "2026-09-08T16:00:00.000Z",
    image_attribution: {
      image_url: "/crafts/jaipur-blue-pottery.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Jaipur_Blue_Pottery_Flower_Vase.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo by Sumeetmoghe, via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 3. Madhubani Painting
  {
    id: "prod-madhubani-03",
    artisan_id: "artisan-sita-devi",
    title: "Handmade Madhubani Kohbar Painting on Cotton Rag Paper",
    title_hi: "हस्तनिर्मित मधुबनी कोहबर चित्रकला (सूती कागज़ पर)",
    description: "Authentic Mithila Kohbar ritual painting depicting fertility, cosmic harmony, and nature blessings. Created using botanical dyes, bamboo nibs, and fine kachni cross-hatching on treated cotton rag paper.",
    description_hi: "प्राकृतिक वनस्पति रंगों, बांस की सींक और हाथ से बने कागज़ पर रचित प्रामाणिक मिथिला कोहबर चित्रकला, जो उर्वरता और प्रकृति के आशीर्वाद का प्रतीक है।",
    category: "paintings",
    craft_name: "Madhubani Painting",
    state: "Bihar",
    district: "Madhubani",
    materials: ["Handmade Cotton Rag Paper", "Turmeric Pigment", "Indigo Dyes", "Lampblack Soot", "Bamboo Nib"],
    motifs: ["Lotus (Kamal)", "Sacred Fish (Matsya)", "Bamboo Grove", "Sun & Moon"],
    dimensions: { length: 56, width: 38, height: 1, unit: "cm" },
    inventory: 4,
    suggested_min_price: 2400,
    suggested_max_price: 3200,
    final_price: 2800,

    price_analysis: {
      id: "pa-madhubani-03",
      product_id: "prod-madhubani-03",
      comparable_count: 5,
      min_price: 2650,
      median_price: 2999,
      max_price: 3500,
      recommended_min: 2400,
      recommended_max: 3200,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 5 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC BiharCrafts).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-mb-1",
                  "product_id": "prod-madhubani-03",
                  "market_price_observation_id": "obs-mb-1",
                  "title": "Authentic Madhubani Hand Painting on Khadi Silk - Tree of Life (22x15 in)",
                  "marketplace": "Amazon",
                  "price": 2999,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08MDB01",
                  "similarity_score": 0.95,
                  "craft_similarity": 0.97,
                  "category_similarity": 0.96,
                  "material_similarity": 0.94,
                  "technique_similarity": 0.95,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Mithila Kohbar & Tree of Life lineage",
                          "Natural plant dyes on khadi silk"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-mb-2",
                  "product_id": "prod-madhubani-03",
                  "market_price_observation_id": "obs-mb-2",
                  "title": "Mithila Folk Art Handmade Khadi Silk Painting Traditional Birds & Lotus",
                  "marketplace": "Flipkart",
                  "price": 2650,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPMDB02",
                  "similarity_score": 0.92,
                  "craft_similarity": 0.95,
                  "category_similarity": 0.92,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Fine nib bamboo pen detailing",
                          "Handmade tussar silk substrate"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-mb-3",
                  "product_id": "prod-madhubani-03",
                  "market_price_observation_id": "obs-mb-3",
                  "title": "Upendra Maharathi Institute Certified Madhubani Folk Scroll",
                  "marketplace": "ONDC (BiharCrafts)",
                  "price": 3200,
                  "currency": "INR",
                  "url": "https://bihar.ondc.org/p/bh-mad-201",
                  "similarity_score": 0.96,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.95,
                  "material_similarity": 0.96,
                  "technique_similarity": 0.96,
                  "size_similarity": 0.94,
                  "handmade_status": true,
                  "match_reasons": [
                          "Certified Mithila artisan guild",
                          "Lampblack & turmeric natural pigments"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-mb-4",
                  "product_id": "prod-madhubani-03",
                  "market_price_observation_id": "obs-mb-4",
                  "title": "Madhubani Heritage Guild Hand-painted Natural Dye Wall Canvas",
                  "marketplace": "Approved Partner",
                  "price": 3500,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/madhubani-3500",
                  "similarity_score": 0.91,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.91,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.91,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Ranti village master artisan work",
                          "Double line fish motif signature"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-madhubani-03",
      recommended_min: 2400,
      recommended_max: 3200,
      final_price: 2800,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 450,
      labor_hours: 18,
      craft_complexity: "High",
      hourly_benchmark: 130,
      fair_wage_subtotal: 2340,
      suggested_min_price: 2400,
      suggested_max_price: 3200,
      ondc_export_markup_suggestion: 3400,
      benchmark_source: "Mithila Artisans Cooperative Benchmark (2025-26)",
      rationale: "Material Cost ₹450 + Estimated Labour (18 hrs fine linework @ ₹130/hr benchmark = ₹2,340). Suggested range ₹2,400 – ₹3,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/madhubani-painting.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Madhubani Handcrafted Art",
    artisan_story: "Learned this art form from my grandmother in Ranti village. Each painting takes 14 days of dedicated hand work using colors ground from turmeric, marigold, and acacia gum.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Madhubani Painting",
      region: "Madhubani, Bihar",
      detected_materials: ["Cotton rag paper", "Organic botanical dyes"],
      detected_motifs: ["Lotus medallion", "Paired fish", "Cosmic celestial motifs"],
      language_detected: "Hindi / Maithili",
      confidence_score: 0.97,
      speech_keywords: ["कोहबर", "मिथिला", "बांस की सींक", "प्राकृतिक रंग", "हल्दी", "नील"],
      visual_features: ["Double-line border framing", "Kachni hatching fill", "Matsya symbol profile"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered GI craft of Mithila region, Bihar (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-madhubani-03",
      product_id: "prod-madhubani-03",
      craft_name: "Madhubani Painting",
      region: "Ranti Village, Madhubani",
      state: "Bihar",
      district: "Madhubani",
      artisan_name: "Sita Devi",
      artisan_lineage: "Ranti Village Women's Painting Collective (4th Generation)",
      traditional_technique: "Freehand line work using bamboo twigs and cotton-tipped styluses; double-line borders filled with intricate hatching (kachni) and vibrant natural pigments (bharni).",
      materials: ["Cotton Rag Paper", "Marigold Pigment", "Indigo Dyes", "Lamp Soot"],
      motifs: ["Kamal (Lotus)", "Matsya (Fertility Fish)", "Bans (Bamboo)"],
      cultural_story: "Originated during the Ramayana period when King Janaka commissioned rural painters for Princess Sita's wedding. Traditionally drawn on the walls of the nuptial chamber (Kohbar Ghar).",
      artisan_story: "Colors are made fresh after monsoons by boiling marigolds and palash flowers.",
      original_language: "Maithili / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "flourishing",
      sources: [
        { title: "Mithila Cultural Heritage Repository", type: "Museum Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-md-1",
          claim_text: "Pigments are 100% natural, extracted from dried marigold petals, neem, and lamp soot.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan declaration & material inspection",
          is_demo_reference: true,
        },
        {
          id: "c-md-2",
          claim_text: "Protected under Geographical Indications of Goods Act .",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-01T10:00:00.000Z",
      updated_at: "2026-09-05T14:30:00.000Z",
    },
    created_at: "2026-09-01T10:00:00.000Z",
    updated_at: "2026-09-05T14:30:00.000Z",
    image_attribution: {
      image_url: "/crafts/madhubani-painting.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Madhubani_painting.jpg",
      license_type: "CC0 / Public Domain",
      attribution_required: true,
      attribution_text: "Public Domain image sourced via Wikimedia Commons",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 4. Channapatna Toys
  {
    id: "prod-channapatna-04",
    artisan_id: "artisan-syed-mubarak",
    title: "Channapatna Non-Toxic Lacquered Wooden Stacking Toy",
    title_hi: "चन्नापट्टना प्राकृतिक लाख एवं काष्ठ बाल खिलौना सेट",
    description: "Eco-friendly educational stacking toy turned on manual lathes using sustainable Hale wood and finished with 100% organic vegetable dyes blended with purified button lac.",
    description_hi: "पर्यावरण-अनुकूल बच्चों का काष्ठ खिलौना, जो हाले की लकड़ी और प्राकृतिक लाख (हल्दी व नील के रंगों) से पारंपरिक खराद पर तैयार किया गया है।",
    category: "woodwork",
    craft_name: "Channapatna Toys",
    state: "Karnataka",
    district: "Ramanagara",
    materials: ["Ivory Wood (Hale Mara)", "Natural Button Lac", "Turmeric Pigment", "Kumkum/Madder", "Palm Leaf Polish"],
    motifs: ["Smooth Cylindrical Contours", "Concentric Ring Geometry"],
    dimensions: { length: 12, width: 12, height: 22, unit: "cm" },
    inventory: 10,
    suggested_min_price: 650,
    suggested_max_price: 900,
    final_price: 750,

    price_analysis: {
      id: "pa-channapatna-04",
      product_id: "prod-channapatna-04",
      comparable_count: 5,
      min_price: 699,
      median_price: 799,
      max_price: 950,
      recommended_min: 650,
      recommended_max: 900,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 5 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC KarnatakaHandicrafts).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-cp-1",
                  "product_id": "prod-channapatna-04",
                  "market_price_observation_id": "obs-cp-1",
                  "title": "Channapatna Handcrafted Natural Wooden Rocking Horse Toy Set",
                  "marketplace": "Amazon",
                  "price": 950,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08CP01",
                  "similarity_score": 0.95,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.96,
                  "material_similarity": 0.95,
                  "technique_similarity": 0.96,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Wrightia tinctoria (Aale mara) wood",
                          "Natural lac and turmeric polish",
                          "Child-safe non-toxic finish"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-cp-2",
                  "product_id": "prod-channapatna-04",
                  "market_price_observation_id": "obs-cp-2",
                  "title": "Eco-Friendly Safe Wooden Lacquerware Toy from Channapatna",
                  "marketplace": "Flipkart",
                  "price": 799,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPCP02",
                  "similarity_score": 0.94,
                  "craft_similarity": 0.96,
                  "category_similarity": 0.94,
                  "material_similarity": 0.92,
                  "technique_similarity": 0.94,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Artisan lathe-turned woodcraft",
                          "Vegetable dye colors"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-cp-3",
                  "product_id": "prod-channapatna-04",
                  "market_price_observation_id": "obs-cp-3",
                  "title": "Cauvery Handicrafts GI Certified Channapatna Wooden Animal Toy",
                  "marketplace": "ONDC (KarnatakaHandicrafts)",
                  "price": 850,
                  "currency": "INR",
                  "url": "https://karnataka.ondc.org/p/kn-toy-301",
                  "similarity_score": 0.97,
                  "craft_similarity": 0.99,
                  "category_similarity": 0.96,
                  "material_similarity": 0.97,
                  "technique_similarity": 0.98,
                  "size_similarity": 0.93,
                  "handmade_status": true,
                  "match_reasons": [
                          "Cauvery Karnataka State certified GI craft",
                          "Natural lac application under friction"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-cp-4",
                  "product_id": "prod-channapatna-04",
                  "market_price_observation_id": "obs-cp-4",
                  "title": "Artisan Guild Channapatna Heirloom Handturned Lacquer Toy",
                  "marketplace": "Approved Partner",
                  "price": 699,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/channapatna-699",
                  "similarity_score": 0.91,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.91,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Traditional power-lathe artisan guild",
                          "Organic Talegari leaf finishing"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-channapatna-04",
      recommended_min: 650,
      recommended_max: 900,
      final_price: 750,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 160,
      labor_hours: 4.5,
      craft_complexity: "Medium",
      hourly_benchmark: 120,
      fair_wage_subtotal: 540,
      suggested_min_price: 650,
      suggested_max_price: 900,
      ondc_export_markup_suggestion: 1050,
      benchmark_source: "Karnataka State Handicrafts Development Benchmark",
      rationale: "Material Cost ₹160 + Estimated Labour (4.5 hrs lathe turning @ ₹120/hr benchmark = ₹540). Child-safe non-toxic natural lac finish. Suggested range ₹650 – ₹900. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/channapatna-toys.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Channapatna Wooden Toys & Lacquerware",
    artisan_story: "My family has turned toys in the 'Gombegala Ooru' (Toy Town) of Channapatna for three generations. We ensure safe, splinter-free toys that bring joy to children while honoring the earth.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Channapatna Toys",
      region: "Channapatna, Karnataka",
      detected_materials: ["Wrightia tinctoria (Hale Mara)", "Natural seedlac"],
      detected_motifs: ["Lathe-turned radial contours", "Vibrant concentric rings"],
      language_detected: "Hindi / Kannada",
      confidence_score: 0.98,
      speech_keywords: ["चन्नापट्टना", "हाले लकड़ी", "प्राकृतिक लाख", "हल्दी", "बाल खिलौना"],
      visual_features: ["Lathe-turned radial symmetry", "High-gloss friction shellac finish", "Vegetable dyed concentric rings"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-channapatna-04",
      product_id: "prod-channapatna-04",
      craft_name: "Channapatna Toys",
      region: "Channapatna, Ramanagara",
      state: "Karnataka",
      district: "Ramanagara",
      artisan_name: "Syed Mubarak",
      artisan_lineage: "Gombegala Ooru Traditional Woodturners Guild",
      traditional_technique: "Wood turning on manual and motorized lathes; friction heat melts button lac sticks blended with plant extracts; polished with screw pine leaves.",
      materials: ["Ivory Wood (Hale)", "Natural Lac", "Turmeric", "Indigo"],
      motifs: ["Concentric Rings", "Rounded Edges"],
      cultural_story: "Introduced during the reign of Tipu Sultan who invited Persian artisans to train local woodturners. One of India's earliest GI-protected crafts.",
      artisan_story: "We only use fallen or pruned Hale wood, never felling live trees. Safe for infants to chew on.",
      original_language: "Kannada / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "flourishing",
      sources: [
        { title: "Karnataka Handicraft Corporation Records", type: "State Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-cp-1",
          claim_text: "100% non-toxic child-safe finish verified with food-grade vegetable dyes.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan workshop compliance declaration",
          is_demo_reference: true,
        },
        {
          id: "c-cp-2",
          claim_text: "GI Registered craft under Geographical Indications Registry India.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-08T08:30:00.000Z",
      updated_at: "2026-09-10T11:00:00.000Z",
    },
    created_at: "2026-09-08T08:30:00.000Z",
    updated_at: "2026-09-10T11:00:00.000Z",
    image_attribution: {
      image_url: "/crafts/channapatna-toys.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Channapatna_toys.jpg",
      license_type: "CC BY-SA 3.0",
      attribution_required: true,
      attribution_text: "Photo via Wikimedia Commons (CC BY-SA 3.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 5. Banarasi Silk Brocade
  {
    id: "prod-banarasi-05",
    artisan_id: "artisan-ansari-brothers",
    title: "Handloom Banarasi Katan Silk Brocade Dupatta with Zari Jaal",
    title_hi: "हथकरघा बनारसी कतान सिल्क ज़री जाल दुपट्टा",
    description: "Pure hand-woven Katan silk stole featuring an all-over floral jaal hand-woven with fine gold and silver electroplated metallic thread (zari) using traditional Naksha drawlooms in Varanasi.",
    description_hi: "शुद्ध हथकरघा कतान सिल्क पर पारंपरिक नक्शा तकनीक से बुना गया स्वर्ण और रजत ज़री का पारंपरिक जाल दुपट्टा।",
    category: "textiles",
    craft_name: "Banarasi Silk Brocade",
    state: "Uttar Pradesh",
    district: "Varanasi",
    materials: ["Pure Mulberry Katan Silk", "Gold-toned Metallic Thread (Zari)", "Natural Silk Warps"],
    motifs: ["Jall (Floral Net)", "Kalka (Paisley)", "Ashrafi (Gold Coin Medallion)"],
    dimensions: { length: 240, width: 90, unit: "cm" },
    inventory: 2,
    suggested_min_price: 8500,
    suggested_max_price: 11000,
    final_price: 9500,

    price_analysis: {
      id: "pa-banarasi-05",
      product_id: "prod-banarasi-05",
      comparable_count: 5,
      min_price: 8800,
      median_price: 9800,
      max_price: 11500,
      recommended_min: 8500,
      recommended_max: 11000,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 5 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC UPHandlooms).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-ban-1",
                  "product_id": "prod-banarasi-05",
                  "market_price_observation_id": "obs-ban-1",
                  "title": "Handloom Pure Katan Silk Banarasi Brocade Dupatta with Real Zari Jaal",
                  "marketplace": "Amazon",
                  "price": 9800,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08BAN01",
                  "similarity_score": 0.96,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.97,
                  "material_similarity": 0.96,
                  "technique_similarity": 0.97,
                  "size_similarity": 0.95,
                  "handmade_status": true,
                  "match_reasons": [
                          "Authentic Katan mulberry silk",
                          "Hand-woven metallic zari jaal",
                          "Varanasi handloom guild origin"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-ban-2",
                  "product_id": "prod-banarasi-05",
                  "market_price_observation_id": "obs-ban-2",
                  "title": "Authentic Varanasi Handwoven Pure Silk Bridal Dupatta Heritage Collection",
                  "marketplace": "Flipkart",
                  "price": 8800,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPBAN02",
                  "similarity_score": 0.93,
                  "craft_similarity": 0.95,
                  "category_similarity": 0.94,
                  "material_similarity": 0.92,
                  "technique_similarity": 0.93,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Naksha drawloom weave",
                          "Intricate floral bootis"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-ban-3",
                  "product_id": "prod-banarasi-05",
                  "market_price_observation_id": "obs-ban-3",
                  "title": "Varanasi Weavers Cooperative GI Certified Katan Silk Brocade Dupatta",
                  "marketplace": "ONDC (UPHandlooms)",
                  "price": 10500,
                  "currency": "INR",
                  "url": "https://uphandlooms.ondc.org/p/up-ban-401",
                  "similarity_score": 0.98,
                  "craft_similarity": 0.99,
                  "category_similarity": 0.98,
                  "material_similarity": 0.98,
                  "technique_similarity": 0.98,
                  "size_similarity": 0.96,
                  "handmade_status": true,
                  "match_reasons": [
                          "Bunkar Seva Kendra certified handloom",
                          "Pure gold-electroplated zari"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-ban-4",
                  "product_id": "prod-banarasi-05",
                  "market_price_observation_id": "obs-ban-4",
                  "title": "Heritage Master Weaver Katan Silk Shikargah Handloom Stole",
                  "marketplace": "Approved Partner",
                  "price": 11500,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/banarasi-11500",
                  "similarity_score": 0.91,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.92,
                  "material_similarity": 0.91,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.91,
                  "handmade_status": true,
                  "match_reasons": [
                          "Master weaver signature piece",
                          "Traditional kadhwa technique"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-banarasi-05",
      recommended_min: 8500,
      recommended_max: 11000,
      final_price: 9500,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 3200,
      labor_hours: 40,
      craft_complexity: "Master",
      hourly_benchmark: 150,
      fair_wage_subtotal: 6000,
      suggested_min_price: 8500,
      suggested_max_price: 11000,
      ondc_export_markup_suggestion: 13500,
      benchmark_source: "Varanasi Bunkar Seva Kendra Handloom Benchmark",
      rationale: "Material Cost ₹3,200 (Pure Katan Silk + Zari) + Estimated Labour (40 hrs master weaving @ ₹150/hr benchmark = ₹6,000). Suggested range ₹8,500 – ₹11,000. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/banarasi-silk.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Banarasi Silk Sarees & Brocades",
    artisan_story: "We are weavers from the Madanpura mohalla of Varanasi. Our loom rhythm is our heartbeat. It takes two artisans working in unison over 12 days to weave this single zari jaal drape.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Banarasi Silk Brocade",
      region: "Varanasi, Uttar Pradesh",
      detected_materials: ["Mulberry Katan silk", "Metallic zari thread"],
      detected_motifs: ["Paisley kalka", "Floral jaal web", "Mughal foliage"],
      language_detected: "Hindi / Urdu",
      confidence_score: 0.95,
      speech_keywords: ["बनारसी", "कतान सिल्क", "ज़री", "हथकरघा", "मदनपुरा", "दुपट्टा"],
      visual_features: ["Densely woven brocade jacquard pattern", "Gold zari metallic shimmer", "Fine silk selvedge edge"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-banarasi-05",
      product_id: "prod-banarasi-05",
      craft_name: "Banarasi Silk Brocade",
      region: "Madanpura, Varanasi",
      state: "Uttar Pradesh",
      district: "Varanasi",
      artisan_name: "Mustaqeem Ansari & Brothers",
      artisan_lineage: "Madanpura Handloom Master Weavers (4th Generation)",
      traditional_technique: "Fekua and Kadhwa handloom weaving using punched card jacquard/naksha mechanism, interweaving supplementary zari weft floats into high-twist mulberry silk warp.",
      materials: ["Katan Silk", "Tested Zari", "Natural Vegetable Dye Silk"],
      motifs: ["Kalka (Paisley)", "Shikargah (Hunting Scenes)", "Beldar (Floral Vines)"],
      cultural_story: "Mentioned in the Buddhist Jatakas and Rigveda, Banarasi brocades reached their artistic zenith during the Mughal era under Emperor Akbar's royal workshops.",
      artisan_story: "Every thread is passed through reed dents by hand. No synthetic polyester or powerloom blend is ever used on our loom.",
      original_language: "Hindi / Urdu",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "high",
      sources: [
        { title: "Varanasi Bunkar Guild Registry", type: "Handloom Federation", is_demo: true }
      ],
      claims: [
        {
          id: "c-bn-1",
          claim_text: "100% handloom woven on pit-loom with authentic mulberry Katan silk warp and weft.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan loom inspection & silk board certification",
          is_demo_reference: true,
        },
        {
          id: "c-bn-2",
          claim_text: "GI Registered craft of Banaras under Geographical Indication Registry India.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-02T12:00:00.000Z",
      updated_at: "2026-09-07T15:00:00.000Z",
    },
    created_at: "2026-09-02T12:00:00.000Z",
    updated_at: "2026-09-07T15:00:00.000Z",
    image_attribution: {
      image_url: "/crafts/banarasi-silk.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Banarasi_Saree.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 6. Kutch Rogan & Embroidery
  {
    id: "prod-kutch-06",
    artisan_id: "artisan-khatri-abdul",
    title: "Kutch Rogan & Rabari Mirror-Work Wall Hanging",
    title_hi: "कच्छ रोगन कला एवं रबारी दर्पण कशीदाकारी दीवार सज्जा",
    description: "Rare castor-seed oil paste freehand painting paired with traditional Rabari geometric mirror-work embroidery on organic indigenous Kala cotton textile.",
    description_hi: "अरंडी के तेल और प्राकृतिक रंगों से हाथ से बनाई गई दुर्लभ रोगन कला एवं पारंपरिक रबारी दर्पण कशीदाकारी से सुसज्जित दीवार सज्जा।",
    category: "textiles",
    craft_name: "Kutch Embroidery & Rogan Art",
    state: "Gujarat",
    district: "Kutch",
    materials: ["Organic Kala Cotton", "Castor Seed Oil (Rogan)", "Natural Stone Pigments", "Convex Mirrors", "Silk Thread"],
    motifs: ["Tree of Life", "Dancing Peacock", "Rabari Geometric Shisha"],
    dimensions: { length: 60, width: 45, unit: "cm" },
    inventory: 3,
    suggested_min_price: 4200,
    suggested_max_price: 5500,
    final_price: 4800,

    price_analysis: {
      id: "pa-kutch-06",
      product_id: "prod-kutch-06",
      comparable_count: 5,
      min_price: 3750,
      median_price: 4400,
      max_price: 4850,
      recommended_min: 4200,
      recommended_max: 5500,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 5 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC GujaratCrafts).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-kt-1",
                  "product_id": "prod-kutch-06",
                  "market_price_observation_id": "obs-kt-1",
                  "title": "Handcrafted Kutch Suf & Mirrorwork Embroidered Wall Hanging (30x20 in)",
                  "marketplace": "Amazon",
                  "price": 4200,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08KT01",
                  "similarity_score": 0.95,
                  "craft_similarity": 0.97,
                  "category_similarity": 0.95,
                  "material_similarity": 0.94,
                  "technique_similarity": 0.96,
                  "size_similarity": 0.93,
                  "handmade_status": true,
                  "match_reasons": [
                          "Kutch Suf geometric counting embroidery",
                          "Hand-cut abhla (mirror) inserts",
                          "Hand-spun cotton substrate"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kt-2",
                  "product_id": "prod-kutch-06",
                  "market_price_observation_id": "obs-kt-2",
                  "title": "Authentic Rabari Tribal Embroidered Tapestry with Mirror Detailing",
                  "marketplace": "Flipkart",
                  "price": 3750,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPKT02",
                  "similarity_score": 0.92,
                  "craft_similarity": 0.94,
                  "category_similarity": 0.92,
                  "material_similarity": 0.91,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.91,
                  "handmade_status": true,
                  "match_reasons": [
                          "Rabari artisan community needlework",
                          "Castor oil Rogan accent borders"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kt-3",
                  "product_id": "prod-kutch-06",
                  "market_price_observation_id": "obs-kt-3",
                  "title": "Gurjari Certified Kutch Artisans Collective Embroidered Heritage Toran",
                  "marketplace": "ONDC (GujaratCrafts)",
                  "price": 4600,
                  "currency": "INR",
                  "url": "https://gujarat.ondc.org/p/gj-kutch-501",
                  "similarity_score": 0.96,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.95,
                  "material_similarity": 0.96,
                  "technique_similarity": 0.97,
                  "size_similarity": 0.94,
                  "handmade_status": true,
                  "match_reasons": [
                          "Gurjari State Handicrafts Development Corporation certified",
                          "Ahir tribal chain stitch masterwork"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kt-4",
                  "product_id": "prod-kutch-06",
                  "market_price_observation_id": "obs-kt-4",
                  "title": "Master Craftswoman Kutch Ahir Hand Embroidered Wall Art",
                  "marketplace": "Approved Partner",
                  "price": 4850,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/kutch-4850",
                  "similarity_score": 0.91,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.91,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Award-winning artisan collective piece",
                          "Traditional peacock and parrot motifs"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-kutch-06",
      recommended_min: 4200,
      recommended_max: 5500,
      final_price: 4800,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 950,
      labor_hours: 26,
      craft_complexity: "Master",
      hourly_benchmark: 140,
      fair_wage_subtotal: 3640,
      suggested_min_price: 4200,
      suggested_max_price: 5500,
      ondc_export_markup_suggestion: 6200,
      benchmark_source: "Kutch Artisan Federation Standard (2025-26)",
      rationale: "Optional internal cost breakdown: Material Cost ₹950 + 26 hrs needlework. Kept separate from external market price discovery.",
    },
    status: "published",
    featured_image_url: "/crafts/kutch-embroidery.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Kutch Handicrafts & Embroideries",
    artisan_story: "Only a single family in Nirona village preserves the ancestral technique of boiling wild castor oil for 48 hours to make the elastic paint dough. We draw patterns in mid-air using a six-inch iron stylus.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Kutch Rogan & Embroidery",
      region: "Nirona, Kutch, Gujarat",
      detected_materials: ["Castor oil paste", "Handspun Kala cotton", "Glass mirrors"],
      detected_motifs: ["Tree of life", "Floral medallions", "Mirror diamonds"],
      language_detected: "Gujarati / Hindi",
      confidence_score: 0.97,
      speech_keywords: ["रोगन", "कच्छ", "अरंडी तेल", "कशीदाकारी", "नीरोना", "दर्पण"],
      visual_features: ["Raised resinous paint lines", "Concentric circular Tree of Life", "Chain stitch mirror frames"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-kutch-06",
      product_id: "prod-kutch-06",
      craft_name: "Kutch Rogan & Embroidery",
      region: "Nirona Village, Kutch",
      state: "Gujarat",
      district: "Kutch",
      artisan_name: "Khatri Abdul Gafur & Rabari Women Collective",
      artisan_lineage: "Nirona Rogan Master Family (8th Generation)",
      traditional_technique: "Castor oil boiled continuously for 48 hours until gelatinous; blended with mineral stone pigments; transferred to palms and drawn onto fabric with a blunt iron stylus without direct stencil.",
      materials: ["Castor Seed Oil", "Kala Cotton", "Mineral Pigments", "Mirrors"],
      motifs: ["Tree of Life", "Peacocks", "Geometric Starbursts"],
      cultural_story: "Originated in Persia and journeyed to Kutch around 400 years ago. Traditionally used to adorn bridal skirts and wedding coverlets.",
      artisan_story: "The stylus never touches the cloth; the thread of paint is guided through the air by hand gesture.",
      original_language: "Gujarati / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "critical",
      sources: [
        { title: "Gujarat State Handloom Development Corporation", type: "State Guild Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-kt-1",
          claim_text: "Hand-boiled castor oil resin drawn freehand without mechanical printing or stencils.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan studio demonstration",
          is_demo_reference: true,
        },
        {
          id: "c-kt-2",
          claim_text: "Registered under Kutch Handicrafts Geographical Indication.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-04T14:00:00.000Z",
      updated_at: "2026-09-09T17:00:00.000Z",
    },
    created_at: "2026-09-04T14:00:00.000Z",
    updated_at: "2026-09-09T17:00:00.000Z",
    image_attribution: {
      image_url: "/crafts/kutch-embroidery.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Kutch_embroidery.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 7. Raghurajpur Pattachitra
  {
    id: "prod-pattachitra-07",
    artisan_id: "artisan-rabindra-maharana",
    title: "Raghurajpur Palm Leaf Pattachitra Scroll - Tree of Life & Dashavatara",
    title_hi: "रघुराजपुर ताड़पत्र पट्टचित्र - दशावतार एवं कल्पवृक्ष",
    description: "Exquisite hand-etched Tala Pattachitra created on seasoned palm leaves stitched together with natural thread. Etched with an iron stylus and stained with soot from lampblack.",
    description_hi: "ताड़ के पत्तों पर लोहे की सुई (लेख्या) से उकेरा गया पारंपरिक पट्टचित्र, जिसमें भगवान विष्णु के दशावतार और कल्पवृक्ष की कथा चित्रित है।",
    category: "paintings",
    craft_name: "Raghurajpur Pattachitra",
    state: "Odisha",
    district: "Puri",
    materials: ["Tala (Dried Palm Leaves)", "Kohl Lamp Soot", "Natural Bean Gum", "Cotton Twine"],
    motifs: ["Dashavatara", "Kalpavriksha (Tree of Life)", "Floral Foliage Borders"],
    dimensions: { length: 45, width: 30, height: 1, unit: "cm" },
    inventory: 3,
    suggested_min_price: 3200,
    suggested_max_price: 4200,
    final_price: 3600,

    price_analysis: {
      id: "pa-pattachitra-07",
      product_id: "prod-pattachitra-07",
      comparable_count: 5,
      min_price: 2899,
      median_price: 3450,
      max_price: 4100,
      recommended_min: 3200,
      recommended_max: 4200,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 5 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC OdishaHandicrafts).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-pat-1",
                  "product_id": "prod-pattachitra-07",
                  "market_price_observation_id": "obs-pat-1",
                  "title": "Traditional Odisha Pattachitra Palm Leaf Engraving Tala Pattachitra (15x10 in)",
                  "marketplace": "Amazon",
                  "price": 3200,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08PAT01",
                  "similarity_score": 0.95,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.96,
                  "material_similarity": 0.95,
                  "technique_similarity": 0.96,
                  "size_similarity": 0.93,
                  "handmade_status": true,
                  "match_reasons": [
                          "Tala Pattachitra treated palm leaf",
                          "Iron stylus engraving with kajal/charcoal infill",
                          "Raghurajpur heritage cluster lineage"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-pat-2",
                  "product_id": "prod-pattachitra-07",
                  "market_price_observation_id": "obs-pat-2",
                  "title": "Raghurajpur Heritage Artisan Hand-Painted Cloth Pattachitra - Krishna Leela",
                  "marketplace": "Flipkart",
                  "price": 2899,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPPAT02",
                  "similarity_score": 0.92,
                  "craft_similarity": 0.94,
                  "category_similarity": 0.92,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Conch-shell white and hingula red natural colors",
                          "Traditional iconographic borders"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-pat-3",
                  "product_id": "prod-pattachitra-07",
                  "market_price_observation_id": "obs-pat-3",
                  "title": "Utkalika Certified Traditional Palm Leaf Pattachitra Folk Scroll",
                  "marketplace": "ONDC (OdishaHandicrafts)",
                  "price": 3700,
                  "currency": "INR",
                  "url": "https://odisha.ondc.org/p/or-pat-601",
                  "similarity_score": 0.97,
                  "craft_similarity": 0.99,
                  "category_similarity": 0.96,
                  "material_similarity": 0.97,
                  "technique_similarity": 0.98,
                  "size_similarity": 0.95,
                  "handmade_status": true,
                  "match_reasons": [
                          "Utkalika Odisha State Apex Handicraft certified",
                          "Interlocking folding palm leaf slats"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-pat-4",
                  "product_id": "prod-pattachitra-07",
                  "market_price_observation_id": "obs-pat-4",
                  "title": "Raghurajpur Heritage Craft Guild Master Pattachitra on Cotton Canvas",
                  "marketplace": "Approved Partner",
                  "price": 4100,
                  "currency": "INR",
                  "url": "https://heritagecrafts.in/p/pattachitra-4100",
                  "similarity_score": 0.91,
                  "craft_similarity": 0.93,
                  "category_similarity": 0.91,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.91,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Master Chitrakar family lineage",
                          "Tamarind seed glue canvas preparation"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-pattachitra-07",
      recommended_min: 3200,
      recommended_max: 4200,
      final_price: 3600,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 600,
      labor_hours: 21,
      craft_complexity: "High",
      hourly_benchmark: 135,
      fair_wage_subtotal: 2835,
      suggested_min_price: 3200,
      suggested_max_price: 4200,
      ondc_export_markup_suggestion: 4800,
      benchmark_source: "Odisha State Crafts Council Standard (2025-26)",
      rationale: "Material Cost ₹600 (Seasoned palm leaves + bean gum) + Estimated Labour (21 hrs microscopic needle incising @ ₹135/hr benchmark = ₹2,835). Suggested range ₹3,200 – ₹4,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/pattachitra.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Puri Pattachitra & Heritage Art",
    artisan_story: "Raghurajpur is India's first heritage craft village. Every household in our village is a living workshop where we dry palm leaves for three months before carving line by line with our iron stylus.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Raghurajpur Pattachitra",
      region: "Puri, Odisha",
      detected_materials: ["Tala palm leaves", "Lampblack soot", "Natural bean adhesive"],
      detected_motifs: ["Dashavatara postures", "Temple spires", "Microscopic leaf scrolling"],
      language_detected: "Odia / Hindi",
      confidence_score: 0.96,
      speech_keywords: ["पट्टचित्र", "रघुराजपुर", "ताड़पत्र", "दशावतार", "पूरी", "स्याही"],
      visual_features: ["Segmented stitched palm leaf panels", "Incised black linework with soot fill", "Classical Odissi iconography"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-pattachitra-07",
      product_id: "prod-pattachitra-07",
      craft_name: "Raghurajpur Pattachitra",
      region: "Raghurajpur Village, Puri",
      state: "Odisha",
      district: "Puri",
      artisan_name: "Rabindra Maharana",
      artisan_lineage: "Raghurajpur Chitrakar Lineage (6th Generation)",
      traditional_technique: "Tala Pattachitra: Palm leaves boiled in turmeric water, dried, stitched with cotton thread, incised with sharp iron stylus (lekhani), and rubbed with lampblack and bean extract to fix the ink.",
      materials: ["Palm Leaves", "Lampblack", "Turmeric Water", "Cotton Thread"],
      motifs: ["Jagannath Icons", "Dashavatara", "Nature Vines"],
      cultural_story: "Intricately linked with Lord Jagannath temple ritual worship in Puri during the Anavasara fortnight when the deities retire from public view.",
      artisan_story: "The palm leaf requires three months of sun and shadow curing so it does not crack under the stylus.",
      original_language: "Odia / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "high",
      sources: [
        { title: "Odisha Lalit Kala Akademi Archive", type: "State Art Institution", is_demo: true }
      ],
      claims: [
        {
          id: "c-pt-1",
          claim_text: "Hand-incised on cured palm leaves using traditional iron stylus and soot rub.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Raghurajpur Crafts Guild Master Roster",
          is_demo_reference: true,
        },
        {
          id: "c-pt-2",
          claim_text: "Recognized under Geographical Indications Registry .",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-05T09:00:00.000Z",
      updated_at: "2026-09-10T14:00:00.000Z",
    },
    created_at: "2026-09-05T09:00:00.000Z",
    updated_at: "2026-09-10T14:00:00.000Z",
    image_attribution: {
      image_url: "/crafts/pattachitra.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Pattachitra.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },

  // 8. Kashmiri Papier-Mâché
  {
    id: "prod-kashmiri-08",
    artisan_id: "artisan-ghulam-nabi",
    title: "Kashmiri Papier-Mâché Floral Trinket Box with Pure Gold Leaf",
    title_hi: "कश्मीरी पेपर-मैशी हस्तनिर्मित आभूषण मंजूषा (स्वर्ण पत्र युक्त)",
    description: "Hand-molded paper pulp decorative box cured with rice paste, smoothened with kashmiri stone, and painted with miniature Gul-o-Bulbul floral motifs and authentic 24k gold leaf lining.",
    description_hi: "शहतूत के पेड़ की छाल और कागज़ की लुगदी से बनी कश्मीरी डिबिया, जिस पर पारंपरिक गुल-ए-बुलबुल और 24 कैरेट स्वर्ण पत्ती से बारीक चित्रकारी की गई है।",
    category: "woodwork",
    craft_name: "Kashmiri Papier-Mâché",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    materials: ["Macerated Waste Paper", "Rice Starch Paste", "Aged Stone Polish", "24k Gold Leaf", "Natural Lacquer"],
    motifs: ["Gul-o-Bulbul (Rose and Nightingale)", "Chinar Leaf", "Almond Paisley (Badam)"],
    dimensions: { length: 14, width: 10, height: 7, unit: "cm" },
    inventory: 4,
    suggested_min_price: 2100,
    suggested_max_price: 2800,
    final_price: 2450,

    price_analysis: {
      id: "pa-kashmiri-08",
      product_id: "prod-kashmiri-08",
      comparable_count: 4,
      min_price: 2299,
      median_price: 2450,
      max_price: 2650,
      recommended_min: 2100,
      recommended_max: 2800,
      confidence: "high",
      evidence_strength: "HIGH",
      approved_sources_count: 3,
      generated_at: "2026-09-11T18:30:00.000Z",
      checked_at: "2026-09-11T18:30:00.000Z",
      explanation: "Recommendation is based on 4 comparable products retrieved from approved market data sources (Amazon, Flipkart, ONDC JKHandicrafts).",
      is_demo_data: true,
      status: "sufficient_data",
      comparables: [
          {
                  "id": "comp-kpm-1",
                  "product_id": "prod-kashmiri-08",
                  "market_price_observation_id": "obs-kpm-1",
                  "title": "Handcrafted Kashmiri Papier-Mâché Floral Trinket Box (15 cm)",
                  "marketplace": "Amazon",
                  "price": 2499,
                  "currency": "INR",
                  "url": "https://www.amazon.in/dp/B08KPM01",
                  "similarity_score": 0.96,
                  "craft_similarity": 0.98,
                  "category_similarity": 0.96,
                  "material_similarity": 0.95,
                  "technique_similarity": 0.97,
                  "size_similarity": 0.94,
                  "handmade_status": true,
                  "match_reasons": [
                          "Sakhtsazi moulded mashed paper core",
                          "Naqqashi fine hair brush floral painting",
                          "Pure gold leaf illumination highlights"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kpm-2",
                  "product_id": "prod-kashmiri-08",
                  "market_price_observation_id": "obs-kpm-2",
                  "title": "Srinagar Artisanal Lacquered Papier-Mâché Gold Foil Jewelry Box",
                  "marketplace": "Flipkart",
                  "price": 2299,
                  "currency": "INR",
                  "url": "https://www.flipkart.com/item/FLPKPM02",
                  "similarity_score": 0.93,
                  "craft_similarity": 0.95,
                  "category_similarity": 0.94,
                  "material_similarity": 0.92,
                  "technique_similarity": 0.93,
                  "size_similarity": 0.92,
                  "handmade_status": true,
                  "match_reasons": [
                          "Zandhari floral pattern",
                          "Multi-layer hand-rubbed lacquer finish"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kpm-3",
                  "product_id": "prod-kashmiri-08",
                  "market_price_observation_id": "obs-kpm-3",
                  "title": "Authentic Kashmir Sakhtsazi Naqashi Papier-Mâché Decorative Box",
                  "marketplace": "ONDC (JKHandicrafts)",
                  "price": 2650,
                  "currency": "INR",
                  "url": "https://jkhandicrafts.ondc.org/p/jk-pm-701",
                  "similarity_score": 0.97,
                  "craft_similarity": 0.99,
                  "category_similarity": 0.96,
                  "material_similarity": 0.97,
                  "technique_similarity": 0.98,
                  "size_similarity": 0.95,
                  "handmade_status": true,
                  "match_reasons": [
                          "J&K Handicrafts Directorate GI tagged cluster",
                          "Pure mineral pigment illumination"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          },
          {
                  "id": "comp-kpm-4",
                  "product_id": "prod-kashmiri-08",
                  "market_price_observation_id": "obs-kpm-4",
                  "title": "Traditional Kashmiri Miniature Naqqashi Papier-Mâché Art Piece",
                  "marketplace": "ONDC (CraftsBazaar)",
                  "price": 2350,
                  "currency": "INR",
                  "url": "https://craftsbazaar.ondc.org/p/cb-9921",
                  "similarity_score": 0.92,
                  "craft_similarity": 0.94,
                  "category_similarity": 0.91,
                  "material_similarity": 0.9,
                  "technique_similarity": 0.92,
                  "size_similarity": 0.9,
                  "handmade_status": true,
                  "match_reasons": [
                          "Handmade pulp foundation",
                          "Gul-ander-gul (flower within flower) motif"
                  ],
                  "retrieved_at": "2026-09-11T18:30:00.000Z",
                  "source_type": "demo_data",
                  "is_demo": true
          }
  ],
    },    artisan_price_decision: {
      product_id: "prod-kashmiri-08",
      recommended_min: 2100,
      recommended_max: 2800,
      final_price: 2450,
      chosen_by: "artisan_manual",
      created_at: "2026-09-11T18:30:00.000Z",
      pricing_sources: ["Amazon", "Flipkart", "ONDC Network"],
    },
    pricing_breakdown: {
      material_cost: 520,
      labor_hours: 14,
      craft_complexity: "High",
      hourly_benchmark: 135,
      fair_wage_subtotal: 1890,
      suggested_min_price: 2100,
      suggested_max_price: 2800,
      ondc_export_markup_suggestion: 3200,
      benchmark_source: "Jammu & Kashmir Directorate of Handicrafts Benchmark",
      rationale: "Material Cost ₹520 (Paper pulp + 24k gold leaf foil) + Estimated Labour (14 hrs fine brush miniature art @ ₹135/hr benchmark = ₹1,890). Suggested range ₹2,100 – ₹2,800. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "/crafts/kashmiri-papier-mache.jpg",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI-Registered Craft",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Kashmir Papier-Mâché Art",
    artisan_story: "My family in Zadibal, Srinagar has carried this craft since Mir Sayyid Ali Hamadani brought Central Asian master craftsmen to the Kashmir Valley in the 14th century.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Kashmiri Papier-Mâché",
      region: "Srinagar, Jammu & Kashmir",
      detected_materials: ["Macerated paper pulp", "24k gold leaf", "Natural varnish"],
      detected_motifs: ["Chinar leaf silhouette", "Gul-o-Bulbul miniature florals", "Gilded border ribbons"],
      language_detected: "Kashmiri / Urdu / Hindi",
      confidence_score: 0.95,
      speech_keywords: ["पेपर मैशी", "कश्मीर", "श्रीनगर", "गुल ए बुलबुल", "सोना", "चिनार"],
      visual_features: ["Molded paper matrix base", "Lacquered smooth finish", "Gold foil illumination"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered craft cluster in Intellectual Property India records (Craft-Level Recognition)",
    },
    heritage_record: {
      id: "hr-kashmiri-08",
      product_id: "prod-kashmiri-08",
      craft_name: "Kashmiri Papier-Mâché",
      region: "Zadibal, Srinagar",
      state: "Jammu & Kashmir",
      district: "Srinagar",
      artisan_name: "Ghulam Nabi & Family",
      artisan_lineage: "Zadibal Papier-Mâché Ustad Tradition (5th Generation)",
      traditional_technique: "Sakhtsazi (molding macerated paper pulp and rice starch into shape) followed by Naqqashi (freehand painting with cat-hair brushes using mineral pigments and gold leaf lacquer).",
      materials: ["Pulp", "Rice Paste", "Gold Foil", "Mineral Oxides"],
      motifs: ["Chinar Leaf", "Gul-o-Bulbul", "Hazara Patterns"],
      cultural_story: "Introduced in the 14th century during the Sultanate period. The craft symbolizes the cross-pollination of Persian aesthetics and Kashmiri floral landscape.",
      artisan_story: "We burnish the molded surface with agate stone until it feels like ivory before painting with brushes made from domestic cat hair.",
      original_language: "Kashmiri / Urdu / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI-Registered Craft",
      preservation_urgency: "high",
      sources: [
        { title: "J&K Directorate of Handicrafts Heritage Registry", type: "State Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-km-1",
          claim_text: "Authentic two-stage Sakhtsazi and Naqqashi hand-molding and painting.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan studio validation and material verification",
          is_demo_reference: true,
        },
        {
          id: "c-km-2",
          claim_text: "GI Registered Handicraft of Jammu & Kashmir .",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Intellectual Property India — Geographical Indications Registry (craft-level reference)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-06T11:00:00.000Z",
      updated_at: "2026-09-10T16:30:00.000Z",
    },
    created_at: "2026-09-06T11:00:00.000Z",
    updated_at: "2026-09-10T16:30:00.000Z",
    image_attribution: {
      image_url: "/crafts/kashmiri-papier-mache.jpg",
      source_name: "Wikimedia Commons",
      source_url: "https://commons.wikimedia.org/wiki/File:Kashmiri_papier_mache.jpg",
      license_type: "CC BY-SA 4.0",
      attribution_required: true,
      attribution_text: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
      retrieved_at: "2026-09-13",
    },
    gi_craft_status: "GI_REGISTERED_CRAFT",
    gi_authorised_user_status: "NOT_VERIFIED",
    gi_official_url: "https://www.ipindia.gov.in/geographical-indications-track-application-list-of-registered-geographical-indications-and-authorised-users-part-a-register-list-of-registered-gi-of-india",
    price_audit_trail: [],
  },
];

// Demo network inquiry events — one per craft product
export const INITIAL_NETWORK_EVENTS: NetworkEvent[] = [
  {
    id: "ne-001",
    product_id: "prod-dokra-01",
    craft_name: "Bastar Dhokra",
    network: "ONDC",
    event_type: "inquiry",
    buyer_region: "Mumbai",
    message: "Interested in bulk order of 10 units for tribal art gallery.",
    created_at: "2026-09-12T10:30:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-002",
    product_id: "prod-blue-pottery-02",
    craft_name: "Jaipur Blue Pottery",
    network: "GeM",
    event_type: "discovery_ping",
    buyer_region: "Delhi",
    message: "Government procurement interest for state guest house decor.",
    created_at: "2026-09-11T14:00:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-003",
    product_id: "prod-madhubani-03",
    craft_name: "Madhubani Painting",
    network: "ONDC",
    event_type: "catalog_sync",
    buyer_region: "Bengaluru",
    message: "Heritage art marketplace listing request.",
    created_at: "2026-09-10T09:00:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-004",
    product_id: "prod-channapatna-04",
    craft_name: "Channapatna Toys",
    network: "TribesIndia",
    event_type: "inquiry",
    buyer_region: "Chennai",
    message: "Educational toy set inquiry for school program.",
    created_at: "2026-09-09T16:30:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-005",
    product_id: "prod-banarasi-05",
    craft_name: "Banarasi Silk",
    network: "ONDC",
    event_type: "rfq",
    buyer_region: "Surat",
    message: "Request for quote — 5 sarees for wedding trousseau.",
    created_at: "2026-09-08T11:00:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-006",
    product_id: "prod-kutch-06",
    craft_name: "Kutch Embroidery",
    network: "Direct",
    event_type: "inquiry",
    buyer_region: "London (Export)",
    message: "Export inquiry for luxury fashion brand collaboration.",
    created_at: "2026-09-07T08:00:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-007",
    product_id: "prod-pattachitra-07",
    craft_name: "Pattachitra",
    network: "GeM",
    event_type: "discovery_ping",
    buyer_region: "Hyderabad",
    message: "Museum acquisition inquiry for cultural heritage collection.",
    created_at: "2026-09-06T15:00:00.000Z",
    mode: "demo",
  },
  {
    id: "ne-008",
    product_id: "prod-kashmiri-08",
    craft_name: "Kashmiri Papier-Mâché",
    network: "ONDC",
    event_type: "inquiry",
    buyer_region: "Dubai (Export)",
    message: "Luxury gifting inquiry for corporate clients in GCC market.",
    created_at: "2026-09-05T12:00:00.000Z",
    mode: "demo",
  },
];
