import { Product } from "./schema";

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Bastar Dhokra (Hero Scenario Artisan: Shanti Devi)
  {
    id: "prod-dokra-01",
    artisan_id: "artisan-shanti-devi",
    title: "Bastar Dhokra Bell Metal Nandi Bull Tribal Figurine",
    title_hi: "बस्तर ढोकरा घंटी धातु नंदी बैल पारंपरिक प्रतिमा",
    description: "Ancient non-ferrous lost-wax bell metal figurine handcrafted by indigenous artisans in Kondagaon, Bastar. Characterized by delicate twisted wax wire detailing, ritual horns, and hollow brass metallurgy.",
    description_hi: "कोंडागांव, बस्तर के पारंपरिक कारीगरों द्वारा लॉस्ट-वैक्स (मोम ढलाई) विधि से निर्मित पीतल और घंटी धातु की दुर्लभ नंदी बैल मूर्ति।",
    category: "metalwork",
    craft_name: "Bastar Dhokra",
    state: "Chhattisgarh",
    district: "Bastar",
    materials: ["Brass Scrap Alloy", "Bell Metal", "Natural Beeswax", "Termite Mound Clay", "River Silt"],
    motifs: ["Spiraled Wax Filigree", "Tribal Sun Eyes", "Ceremonial Bell Collar", "Sacred Horns"],
    dimensions: { length: 18, width: 10, height: 16, unit: "cm" },
    inventory: 3,
    suggested_min_price: 3500,
    suggested_max_price: 4500,
    final_price: 3900,
    pricing_breakdown: {
      material_cost: 850,
      labor_hours: 22,
      craft_complexity: "High",
      hourly_benchmark: 140,
      fair_wage_subtotal: 3080,
      suggested_min_price: 3500,
      suggested_max_price: 4500,
      ondc_export_markup_suggestion: 5100,
      benchmark_source: "Chhattisgarh Tribal Artisan Guild Guideline (2025-26)",
      rationale: "Material Cost ₹850 + Estimated Labour (22 hrs @ ₹140/hr benchmark = ₹3,080) with High craft complexity. Suggested range ₹3,500 – ₹4,500. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
    additional_images: [
      "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=800&q=80"
    ],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #83 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null, // No fake government identifier
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Bastar Bell Metal Handicrafts",
    artisan_story: "Our family in Kondagaon has practiced this unbroken 4,000-year-old Indus Valley metallurgy across 5 generations. The single-use clay mold is broken open to reveal the metal sculpture, making every single creation irreplaceable.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Bastar Dhokra",
      region: "Bastar, Chhattisgarh",
      detected_materials: ["Bell metal alloy", "Natural beeswax", "Termite refractory clay"],
      detected_motifs: ["Spiraled wax filigree", "Tribal animal morphology", "Nandi bull profile"],
      language_detected: "Hindi",
      confidence_score: 0.96,
      speech_keywords: ["ढोकरा", "घंटी धातु", "मोम ढलाई", "बस्तर", "नंदी बैल", "पीतल"],
      visual_features: ["Twisted wax filigree pattern", "Hollow core bronze casting", "Tribal horned bovine silhouette"],
      safety_check_passed: true,
      gi_candidacy_note: "Matches registered Bastar Dhokra craft cluster in Intellectual Property India records (Demo Reference #83)",
    },
    heritage_record: {
      id: "hr-dokra-01",
      product_id: "prod-dokra-01",
      craft_name: "Bastar Dhokra",
      region: "Kondagaon, Bastar",
      state: "Chhattisgarh",
      district: "Bastar",
      artisan_name: "Shanti Devi & Budhram Baghel",
      artisan_lineage: "Ghadwa tribal brass-casters lineage (5th Generation)",
      traditional_technique: "Cire-Perdue (Lost Wax) Indigenous Metallurgy: Clay core shaped from termite soil, wound with hand-drawn beeswax threads, encased in refractory mud, and poured with liquid scrap bell metal in an open hearth.",
      materials: ["Scrap Brass", "Bell Metal", "Bee Wax", "Termite Mound Clay"],
      motifs: ["Twisted wax filigree", "Tribal Sun Eyes", "Ceremonial Neck Bells"],
      cultural_story: "Direct continuum with the iconic 'Dancing Girl of Mohenjo-Daro' bronze (c. 2300 BCE). For the tribal communities of Bastar, Dhokra sculptures serve as ritual protectors and totems.",
      artisan_story: "We gather beeswax from local sal forests and river clay from the Indravati riverbanks. The mold must be broken to birth the artifact.",
      original_language: "Hindi / Gondi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #83 (Demo Reference)",
      preservation_urgency: "high",
      sources: [
        { title: "Bastar Tribal Craft Guild Documentation", type: "Guild Archive", is_demo: true },
        { title: "National Crafts Council India - Lost Wax Register", type: "Government Heritage Record", is_demo: true }
      ],
      claims: [
        {
          id: "c-dokra-1",
          claim_text: "Single-mold lost wax casting with no mechanical joints or identical duplicates.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan spoken declaration & workshop process review",
          is_demo_reference: true,
        },
        {
          id: "c-dokra-2",
          claim_text: "Recognized as indigenous Bastar Dhokra handicraft under GI Registry documentation.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "Government GI Registry India (Demo Reference #83)",
          is_demo_reference: true,
        },
        {
          id: "c-dokra-3",
          claim_text: "Beeswax winding density indicates Grade-A master Ghadwa lineage technique.",
          source_type: "ai",
          provenance_label: "AI Suggested",
          verification_status: "requires_verification",
          source_reference: "AI surface geometry measurement — requires guild verification",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-01T10:00:00.000Z",
      updated_at: "2026-09-05T14:30:00.000Z",
    },
    created_at: "2026-09-01T10:00:00.000Z",
    updated_at: "2026-09-05T14:30:00.000Z",
  },

  // 2. Jaipur Blue Pottery
  {
    id: "prod-blue-pottery-02",
    artisan_id: "artisan-ramesh-kripal",
    title: "Handcrafted Jaipur Blue Pottery Floral Motif Vase",
    title_hi: "हस्तनिर्मित जयपुर ब्लू पॉटरी फ्लोरल फूलदान",
    description: "Unique low-fire ceramic vase crafted without clay using powdered quartz stone, cullet glass, multani mitti, and natural plant gums. Hand-painted with Persian cobalt blue and turquoise floral arabesques.",
    description_hi: "पारंपरिक जयपुर तकनीक से बिना मिट्टी के क्वार्ट्ज़ और मुल्तानी मिट्टी से निर्मित फूलदान, जिस पर कोबाल्ट नीले और फिरोज़ी रंगों से पारंपरिक बेल-बूटे उकेरे गए हैं।",
    category: "pottery",
    craft_name: "Jaipur Blue Pottery",
    state: "Rajasthan",
    district: "Jaipur",
    materials: ["Ground Quartz Stone", "Cullet Glass", "Multani Mitti", "Natural Borax", "Cobalt Oxide Pigment"],
    motifs: ["Persian Floral Arabesque", "Lotus Rosette", "Geometrical Neck Bands"],
    dimensions: { length: 15, width: 15, height: 28, unit: "cm" },
    inventory: 5,
    suggested_min_price: 1600,
    suggested_max_price: 2200,
    final_price: 1850,
    pricing_breakdown: {
      material_cost: 380,
      labor_hours: 11,
      craft_complexity: "Medium",
      hourly_benchmark: 135,
      fair_wage_subtotal: 1485,
      suggested_min_price: 1600,
      suggested_max_price: 2200,
      ondc_export_markup_suggestion: 2450,
      benchmark_source: "Rajasthan State Handloom & Handicrafts Benchmark",
      rationale: "Material Cost ₹380 + Estimated Labour (11 hrs @ ₹135/hr benchmark = ₹1,485). Suggested range ₹1,600 – ₹2,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #66 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Jaipur Ceramic Arts",
    artisan_story: "My family has practiced this delicate craft in Kot Jewar under the patronage of Jaipur master traditions. Every piece is shaped on the mold by hand and fired in a single wood-kiln cycle.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Jaipur Blue Pottery",
      region: "Jaipur, Rajasthan",
      detected_materials: ["Quartz stone powder", "Glass frit", "Cobalt oxide"],
      detected_motifs: ["Persian arabesque", "Foliage scrolls"],
      language_detected: "Hindi",
      confidence_score: 0.94,
      speech_keywords: ["ब्लू पॉटरी", "क्वार्ट्ज़", "मुल्तानी मिट्टी", "कोबाल्ट नीला", "बिना मिट्टी"],
      visual_features: ["Cobalt blue glaze gloss", "Turquoise botanical infill", "Semi-porous non-thrown body"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication in Jaipur cluster (Demo Reference #66)",
    },
    heritage_record: {
      id: "hr-blue-pottery-02",
      product_id: "prod-blue-pottery-02",
      craft_name: "Jaipur Blue Pottery",
      region: "Kot Jewar, Jaipur",
      state: "Rajasthan",
      district: "Jaipur",
      artisan_name: "Ramesh Kripal",
      artisan_lineage: "Kot Jewar Pottery Guild (Kripal Kumbh disciples)",
      traditional_technique: "Clay-free Egyptian faience-derived ceramic: Quartz powder mixed with saji, katira gond, and glass, pressed in open plaster moulds, painted freehand with metal oxides, and single-fired at 800°C.",
      materials: ["Quartz Powder", "Cullet Glass", "Katira Gond", "Cobalt Oxide"],
      motifs: ["Persian Floral Arabesque", "Foliage Scrolls", "Geometrical Borders"],
      cultural_story: "Introduced to Jaipur by Maharaja Sawai Ram Singh II in the 19th century after seeing kite-flying glazed cords. Renowned for its radiant turquoise hues and imperviousness to cracking.",
      artisan_story: "We do not touch river clay. The quartz is ground into white flour and mixed with natural gum resin.",
      original_language: "Hindi / Rajasthani",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #66 (Demo Reference)",
      preservation_urgency: "medium",
      sources: [
        { title: "Jaipur Blue Pottery Guild Archives", type: "Regional Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-bp-1",
          claim_text: "100% clay-free composition formulated exclusively from Rajasthan mineral quartz.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan declaration & kiln record",
          is_demo_reference: true,
        },
        {
          id: "c-bp-2",
          claim_text: "Geographical Indication recognized craft of Jaipur district.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #66)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-03T11:20:00.000Z",
      updated_at: "2026-09-08T16:00:00.000Z",
    },
    created_at: "2026-09-03T11:20:00.000Z",
    updated_at: "2026-09-08T16:00:00.000Z",
  },

  // 3. Madhubani Painting
  {
    id: "prod-madhubani-03",
    artisan_id: "artisan-sita-devi",
    title: "Handmade Madhubani Kohbar Painting on Cotton Rag Paper",
    title_hi: "हस्तनिर्मित मधुबनी कोहबर चित्रकला (सूती कागज़ पर)",
    description: "Authentic Mithila Kohbar ritual painting depicting fertility, cosmic harmony, and nature blessings. Created using botanical dyes, bamboo nibs, and fine kachni cross-hatching on treated cotton rag paper.",
    description_hi: "प्राकृतिक वनस्पति रंगों, बांस की सींक और हाथ से बने कागज़ पर रचित प्रामाणिक मिथिला कोहबर चित्रकला, जो उर्वरता और प्रकृति के आशीर्वाद का प्रतीक है।",
    category: "paintings",
    craft_name: "Madhubani Painting",
    state: "Bihar",
    district: "Madhubani",
    materials: ["Handmade Cotton Rag Paper", "Turmeric Pigment", "Indigo Dyes", "Lampblack Soot", "Bamboo Nib"],
    motifs: ["Lotus (Kamal)", "Sacred Fish (Matsya)", "Bamboo Grove", "Sun & Moon"],
    dimensions: { length: 56, width: 38, height: 1, unit: "cm" },
    inventory: 4,
    suggested_min_price: 2400,
    suggested_max_price: 3200,
    final_price: 2800,
    pricing_breakdown: {
      material_cost: 450,
      labor_hours: 18,
      craft_complexity: "High",
      hourly_benchmark: 130,
      fair_wage_subtotal: 2340,
      suggested_min_price: 2400,
      suggested_max_price: 3200,
      ondc_export_markup_suggestion: 3400,
      benchmark_source: "Mithila Artisans Cooperative Benchmark (2025-26)",
      rationale: "Material Cost ₹450 + Estimated Labour (18 hrs fine linework @ ₹130/hr benchmark = ₹2,340). Suggested range ₹2,400 – ₹3,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #45 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Madhubani Handcrafted Art",
    artisan_story: "Learned this art form from my grandmother in Ranti village. Each painting takes 14 days of dedicated hand work using colors ground from turmeric, marigold, and acacia gum.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Madhubani Painting",
      region: "Madhubani, Bihar",
      detected_materials: ["Cotton rag paper", "Organic botanical dyes"],
      detected_motifs: ["Lotus medallion", "Paired fish", "Cosmic celestial motifs"],
      language_detected: "Hindi / Maithili",
      confidence_score: 0.97,
      speech_keywords: ["कोहबर", "मिथिला", "बांस की सींक", "प्राकृतिक रंग", "हल्दी", "नील"],
      visual_features: ["Double-line border framing", "Kachni hatching fill", "Matsya symbol profile"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered GI craft of Mithila region, Bihar (Demo Reference #45)",
    },
    heritage_record: {
      id: "hr-madhubani-03",
      product_id: "prod-madhubani-03",
      craft_name: "Madhubani Painting",
      region: "Ranti Village, Madhubani",
      state: "Bihar",
      district: "Madhubani",
      artisan_name: "Sita Devi",
      artisan_lineage: "Ranti Village Women's Painting Collective (4th Generation)",
      traditional_technique: "Freehand line work using bamboo twigs and cotton-tipped styluses; double-line borders filled with intricate hatching (kachni) and vibrant natural pigments (bharni).",
      materials: ["Cotton Rag Paper", "Marigold Pigment", "Indigo Dyes", "Lamp Soot"],
      motifs: ["Kamal (Lotus)", "Matsya (Fertility Fish)", "Bans (Bamboo)"],
      cultural_story: "Originated during the Ramayana period when King Janaka commissioned rural painters for Princess Sita's wedding. Traditionally drawn on the walls of the nuptial chamber (Kohbar Ghar).",
      artisan_story: "Colors are made fresh after monsoons by boiling marigolds and palash flowers.",
      original_language: "Maithili / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #45 (Demo Reference)",
      preservation_urgency: "flourishing",
      sources: [
        { title: "Mithila Cultural Heritage Repository", type: "Museum Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-md-1",
          claim_text: "Pigments are 100% natural, extracted from dried marigold petals, neem, and lamp soot.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan declaration & material inspection",
          is_demo_reference: true,
        },
        {
          id: "c-md-2",
          claim_text: "Protected under Geographical Indications of Goods Act (Demo Reference #45).",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #45)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-01T10:00:00.000Z",
      updated_at: "2026-09-05T14:30:00.000Z",
    },
    created_at: "2026-09-01T10:00:00.000Z",
    updated_at: "2026-09-05T14:30:00.000Z",
  },

  // 4. Channapatna Toys
  {
    id: "prod-channapatna-04",
    artisan_id: "artisan-syed-mubarak",
    title: "Channapatna Non-Toxic Lacquered Wooden Stacking Toy",
    title_hi: "चन्नापट्टना प्राकृतिक लाख एवं काष्ठ बाल खिलौना सेट",
    description: "Eco-friendly educational stacking toy turned on manual lathes using sustainable Hale wood and finished with 100% organic vegetable dyes blended with purified button lac.",
    description_hi: "पर्यावरण-अनुकूल बच्चों का काष्ठ खिलौना, जो हाले की लकड़ी और प्राकृतिक लाख (हल्दी व नील के रंगों) से पारंपरिक खराद पर तैयार किया गया है।",
    category: "woodwork",
    craft_name: "Channapatna Toys",
    state: "Karnataka",
    district: "Ramanagara",
    materials: ["Ivory Wood (Hale Mara)", "Natural Button Lac", "Turmeric Pigment", "Kumkum/Madder", "Palm Leaf Polish"],
    motifs: ["Smooth Cylindrical Contours", "Concentric Ring Geometry"],
    dimensions: { length: 12, width: 12, height: 22, unit: "cm" },
    inventory: 10,
    suggested_min_price: 650,
    suggested_max_price: 900,
    final_price: 750,
    pricing_breakdown: {
      material_cost: 160,
      labor_hours: 4.5,
      craft_complexity: "Medium",
      hourly_benchmark: 120,
      fair_wage_subtotal: 540,
      suggested_min_price: 650,
      suggested_max_price: 900,
      ondc_export_markup_suggestion: 1050,
      benchmark_source: "Karnataka State Handicrafts Development Benchmark",
      rationale: "Material Cost ₹160 + Estimated Labour (4.5 hrs lathe turning @ ₹120/hr benchmark = ₹540). Child-safe non-toxic natural lac finish. Suggested range ₹650 – ₹900. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #19 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Channapatna Wooden Toys & Lacquerware",
    artisan_story: "My family has turned toys in the 'Gombegala Ooru' (Toy Town) of Channapatna for three generations. We ensure safe, splinter-free toys that bring joy to children while honoring the earth.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Channapatna Toys",
      region: "Channapatna, Karnataka",
      detected_materials: ["Wrightia tinctoria (Hale Mara)", "Natural seedlac"],
      detected_motifs: ["Lathe-turned radial contours", "Vibrant concentric rings"],
      language_detected: "Hindi / Kannada",
      confidence_score: 0.98,
      speech_keywords: ["चन्नापट्टना", "हाले लकड़ी", "प्राकृतिक लाख", "हल्दी", "बाल खिलौना"],
      visual_features: ["Lathe-turned radial symmetry", "High-gloss friction shellac finish", "Vegetable dyed concentric rings"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication in Karnataka (Demo Reference #19)",
    },
    heritage_record: {
      id: "hr-channapatna-04",
      product_id: "prod-channapatna-04",
      craft_name: "Channapatna Toys",
      region: "Channapatna, Ramanagara",
      state: "Karnataka",
      district: "Ramanagara",
      artisan_name: "Syed Mubarak",
      artisan_lineage: "Gombegala Ooru Traditional Woodturners Guild",
      traditional_technique: "Wood turning on manual and motorized lathes; friction heat melts button lac sticks blended with plant extracts; polished with screw pine leaves.",
      materials: ["Ivory Wood (Hale)", "Natural Lac", "Turmeric", "Indigo"],
      motifs: ["Concentric Rings", "Rounded Edges"],
      cultural_story: "Introduced during the reign of Tipu Sultan who invited Persian artisans to train local woodturners. One of India's earliest GI-protected crafts.",
      artisan_story: "We only use fallen or pruned Hale wood, never felling live trees. Safe for infants to chew on.",
      original_language: "Kannada / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #19 (Demo Reference)",
      preservation_urgency: "flourishing",
      sources: [
        { title: "Karnataka Handicraft Corporation Records", type: "State Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-cp-1",
          claim_text: "100% non-toxic child-safe finish verified with food-grade vegetable dyes.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan workshop compliance declaration",
          is_demo_reference: true,
        },
        {
          id: "c-cp-2",
          claim_text: "GI Registered craft under Geographical Indications Registry India.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #19)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-08T08:30:00.000Z",
      updated_at: "2026-09-10T11:00:00.000Z",
    },
    created_at: "2026-09-08T08:30:00.000Z",
    updated_at: "2026-09-10T11:00:00.000Z",
  },

  // 5. Banarasi Silk Brocade
  {
    id: "prod-banarasi-05",
    artisan_id: "artisan-ansari-brothers",
    title: "Handloom Banarasi Katan Silk Brocade Dupatta with Zari Jaal",
    title_hi: "हथकरघा बनारसी कतान सिल्क ज़री जाल दुपट्टा",
    description: "Pure hand-woven Katan silk stole featuring an all-over floral jaal hand-woven with fine gold and silver electroplated metallic thread (zari) using traditional Naksha drawlooms in Varanasi.",
    description_hi: "शुद्ध हथकरघा कतान सिल्क पर पारंपरिक नक्शा तकनीक से बुना गया स्वर्ण और रजत ज़री का पारंपरिक जाल दुपट्टा।",
    category: "textiles",
    craft_name: "Banarasi Silk Brocade",
    state: "Uttar Pradesh",
    district: "Varanasi",
    materials: ["Pure Mulberry Katan Silk", "Gold-toned Metallic Thread (Zari)", "Natural Silk Warps"],
    motifs: ["Jall (Floral Net)", "Kalka (Paisley)", "Ashrafi (Gold Coin Medallion)"],
    dimensions: { length: 240, width: 90, unit: "cm" },
    inventory: 2,
    suggested_min_price: 8500,
    suggested_max_price: 11000,
    final_price: 9500,
    pricing_breakdown: {
      material_cost: 3200,
      labor_hours: 40,
      craft_complexity: "Master",
      hourly_benchmark: 150,
      fair_wage_subtotal: 6000,
      suggested_min_price: 8500,
      suggested_max_price: 11000,
      ondc_export_markup_suggestion: 13500,
      benchmark_source: "Varanasi Bunkar Seva Kendra Handloom Benchmark",
      rationale: "Material Cost ₹3,200 (Pure Katan Silk + Zari) + Estimated Labour (40 hrs master weaving @ ₹150/hr benchmark = ₹6,000). Suggested range ₹8,500 – ₹11,000. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #99 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Banarasi Silk Sarees & Brocades",
    artisan_story: "We are weavers from the Madanpura mohalla of Varanasi. Our loom rhythm is our heartbeat. It takes two artisans working in unison over 12 days to weave this single zari jaal drape.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Banarasi Silk Brocade",
      region: "Varanasi, Uttar Pradesh",
      detected_materials: ["Mulberry Katan silk", "Metallic zari thread"],
      detected_motifs: ["Paisley kalka", "Floral jaal web", "Mughal foliage"],
      language_detected: "Hindi / Urdu",
      confidence_score: 0.95,
      speech_keywords: ["बनारसी", "कतान सिल्क", "ज़री", "हथकरघा", "मदनपुरा", "दुपट्टा"],
      visual_features: ["Densely woven brocade jacquard pattern", "Gold zari metallic shimmer", "Fine silk selvedge edge"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication in Varanasi handloom cluster (Demo Reference #99)",
    },
    heritage_record: {
      id: "hr-banarasi-05",
      product_id: "prod-banarasi-05",
      craft_name: "Banarasi Silk Brocade",
      region: "Madanpura, Varanasi",
      state: "Uttar Pradesh",
      district: "Varanasi",
      artisan_name: "Mustaqeem Ansari & Brothers",
      artisan_lineage: "Madanpura Handloom Master Weavers (4th Generation)",
      traditional_technique: "Fekua and Kadhwa handloom weaving using punched card jacquard/naksha mechanism, interweaving supplementary zari weft floats into high-twist mulberry silk warp.",
      materials: ["Katan Silk", "Tested Zari", "Natural Vegetable Dye Silk"],
      motifs: ["Kalka (Paisley)", "Shikargah (Hunting Scenes)", "Beldar (Floral Vines)"],
      cultural_story: "Mentioned in the Buddhist Jatakas and Rigveda, Banarasi brocades reached their artistic zenith during the Mughal era under Emperor Akbar's royal workshops.",
      artisan_story: "Every thread is passed through reed dents by hand. No synthetic polyester or powerloom blend is ever used on our loom.",
      original_language: "Hindi / Urdu",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #99 (Demo Reference)",
      preservation_urgency: "high",
      sources: [
        { title: "Varanasi Bunkar Guild Registry", type: "Handloom Federation", is_demo: true }
      ],
      claims: [
        {
          id: "c-bn-1",
          claim_text: "100% handloom woven on pit-loom with authentic mulberry Katan silk warp and weft.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan loom inspection & silk board certification",
          is_demo_reference: true,
        },
        {
          id: "c-bn-2",
          claim_text: "GI Registered craft of Banaras under Geographical Indication Registry India.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #99)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-02T12:00:00.000Z",
      updated_at: "2026-09-07T15:00:00.000Z",
    },
    created_at: "2026-09-02T12:00:00.000Z",
    updated_at: "2026-09-07T15:00:00.000Z",
  },

  // 6. Kutch Rogan & Embroidery
  {
    id: "prod-kutch-06",
    artisan_id: "artisan-khatri-abdul",
    title: "Kutch Rogan & Rabari Mirror-Work Wall Hanging",
    title_hi: "कच्छ रोगन कला एवं रबारी दर्पण कशीदाकारी दीवार सज्जा",
    description: "Rare castor-seed oil paste freehand painting paired with traditional Rabari geometric mirror-work embroidery on organic indigenous Kala cotton textile.",
    description_hi: "अरंडी के तेल और प्राकृतिक रंगों से हाथ से बनाई गई दुर्लभ रोगन कला एवं पारंपरिक रबारी दर्पण कशीदाकारी से सुसज्जित दीवार सज्जा।",
    category: "textiles",
    craft_name: "Kutch Embroidery & Rogan Art",
    state: "Gujarat",
    district: "Kutch",
    materials: ["Organic Kala Cotton", "Castor Seed Oil (Rogan)", "Natural Stone Pigments", "Convex Mirrors", "Silk Thread"],
    motifs: ["Tree of Life", "Dancing Peacock", "Rabari Geometric Shisha"],
    dimensions: { length: 60, width: 45, unit: "cm" },
    inventory: 3,
    suggested_min_price: 4200,
    suggested_max_price: 5500,
    final_price: 4800,
    pricing_breakdown: {
      material_cost: 950,
      labor_hours: 26,
      craft_complexity: "Master",
      hourly_benchmark: 140,
      fair_wage_subtotal: 3640,
      suggested_min_price: 4200,
      suggested_max_price: 5500,
      ondc_export_markup_suggestion: 6200,
      benchmark_source: "Kutch Artisan Federation Standard (2025-26)",
      rationale: "Material Cost ₹950 (Heated castor oil paste + hand-loomed Kala cotton) + Estimated Labour (26 hrs needle drawing and mirror tacking @ ₹140/hr = ₹3,640). Suggested range ₹4,200 – ₹5,500. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #112 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Kutch Handicrafts & Embroideries",
    artisan_story: "Only a single family in Nirona village preserves the ancestral technique of boiling wild castor oil for 48 hours to make the elastic paint dough. We draw patterns in mid-air using a six-inch iron stylus.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Kutch Rogan & Embroidery",
      region: "Nirona, Kutch, Gujarat",
      detected_materials: ["Castor oil paste", "Handspun Kala cotton", "Glass mirrors"],
      detected_motifs: ["Tree of life", "Floral medallions", "Mirror diamonds"],
      language_detected: "Gujarati / Hindi",
      confidence_score: 0.97,
      speech_keywords: ["रोगन", "कच्छ", "अरंडी तेल", "कशीदाकारी", "नीरोना", "दर्पण"],
      visual_features: ["Raised resinous paint lines", "Concentric circular Tree of Life", "Chain stitch mirror frames"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication for Kutch Embroidery (Demo Reference #112)",
    },
    heritage_record: {
      id: "hr-kutch-06",
      product_id: "prod-kutch-06",
      craft_name: "Kutch Rogan & Embroidery",
      region: "Nirona Village, Kutch",
      state: "Gujarat",
      district: "Kutch",
      artisan_name: "Khatri Abdul Gafur & Rabari Women Collective",
      artisan_lineage: "Nirona Rogan Master Family (8th Generation)",
      traditional_technique: "Castor oil boiled continuously for 48 hours until gelatinous; blended with mineral stone pigments; transferred to palms and drawn onto fabric with a blunt iron stylus without direct stencil.",
      materials: ["Castor Seed Oil", "Kala Cotton", "Mineral Pigments", "Mirrors"],
      motifs: ["Tree of Life", "Peacocks", "Geometric Starbursts"],
      cultural_story: "Originated in Persia and journeyed to Kutch around 400 years ago. Traditionally used to adorn bridal skirts and wedding coverlets.",
      artisan_story: "The stylus never touches the cloth; the thread of paint is guided through the air by hand gesture.",
      original_language: "Gujarati / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #112 (Demo Reference)",
      preservation_urgency: "critical",
      sources: [
        { title: "Gujarat State Handloom Development Corporation", type: "State Guild Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-kt-1",
          claim_text: "Hand-boiled castor oil resin drawn freehand without mechanical printing or stencils.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan studio demonstration",
          is_demo_reference: true,
        },
        {
          id: "c-kt-2",
          claim_text: "Registered under Kutch Handicrafts Geographical Indication.",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #112)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-04T14:00:00.000Z",
      updated_at: "2026-09-09T17:00:00.000Z",
    },
    created_at: "2026-09-04T14:00:00.000Z",
    updated_at: "2026-09-09T17:00:00.000Z",
  },

  // 7. Raghurajpur Pattachitra
  {
    id: "prod-pattachitra-07",
    artisan_id: "artisan-rabindra-maharana",
    title: "Raghurajpur Palm Leaf Pattachitra Scroll - Tree of Life & Dashavatara",
    title_hi: "रघुराजपुर ताड़पत्र पट्टचित्र - दशावतार एवं कल्पवृक्ष",
    description: "Exquisite hand-etched Tala Pattachitra created on seasoned palm leaves stitched together with natural thread. Etched with an iron stylus and stained with soot from lampblack.",
    description_hi: "ताड़ के पत्तों पर लोहे की सुई (लेख्या) से उकेरा गया पारंपरिक पट्टचित्र, जिसमें भगवान विष्णु के दशावतार और कल्पवृक्ष की कथा चित्रित है।",
    category: "paintings",
    craft_name: "Raghurajpur Pattachitra",
    state: "Odisha",
    district: "Puri",
    materials: ["Tala (Dried Palm Leaves)", "Kohl Lamp Soot", "Natural Bean Gum", "Cotton Twine"],
    motifs: ["Dashavatara", "Kalpavriksha (Tree of Life)", "Floral Foliage Borders"],
    dimensions: { length: 45, width: 30, height: 1, unit: "cm" },
    inventory: 3,
    suggested_min_price: 3200,
    suggested_max_price: 4200,
    final_price: 3600,
    pricing_breakdown: {
      material_cost: 600,
      labor_hours: 21,
      craft_complexity: "High",
      hourly_benchmark: 135,
      fair_wage_subtotal: 2835,
      suggested_min_price: 3200,
      suggested_max_price: 4200,
      ondc_export_markup_suggestion: 4800,
      benchmark_source: "Odisha State Crafts Council Standard (2025-26)",
      rationale: "Material Cost ₹600 (Seasoned palm leaves + bean gum) + Estimated Labour (21 hrs microscopic needle incising @ ₹135/hr benchmark = ₹2,835). Suggested range ₹3,200 – ₹4,200. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #87 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Puri Pattachitra & Heritage Art",
    artisan_story: "Raghurajpur is India's first heritage craft village. Every household in our village is a living workshop where we dry palm leaves for three months before carving line by line with our iron stylus.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Raghurajpur Pattachitra",
      region: "Puri, Odisha",
      detected_materials: ["Tala palm leaves", "Lampblack soot", "Natural bean adhesive"],
      detected_motifs: ["Dashavatara postures", "Temple spires", "Microscopic leaf scrolling"],
      language_detected: "Odia / Hindi",
      confidence_score: 0.96,
      speech_keywords: ["पट्टचित्र", "रघुराजपुर", "ताड़पत्र", "दशावतार", "पूरी", "स्याही"],
      visual_features: ["Segmented stitched palm leaf panels", "Incised black linework with soot fill", "Classical Odissi iconography"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication in Odisha (Demo Reference #87)",
    },
    heritage_record: {
      id: "hr-pattachitra-07",
      product_id: "prod-pattachitra-07",
      craft_name: "Raghurajpur Pattachitra",
      region: "Raghurajpur Village, Puri",
      state: "Odisha",
      district: "Puri",
      artisan_name: "Rabindra Maharana",
      artisan_lineage: "Raghurajpur Chitrakar Lineage (6th Generation)",
      traditional_technique: "Tala Pattachitra: Palm leaves boiled in turmeric water, dried, stitched with cotton thread, incised with sharp iron stylus (lekhani), and rubbed with lampblack and bean extract to fix the ink.",
      materials: ["Palm Leaves", "Lampblack", "Turmeric Water", "Cotton Thread"],
      motifs: ["Jagannath Icons", "Dashavatara", "Nature Vines"],
      cultural_story: "Intricately linked with Lord Jagannath temple ritual worship in Puri during the Anavasara fortnight when the deities retire from public view.",
      artisan_story: "The palm leaf requires three months of sun and shadow curing so it does not crack under the stylus.",
      original_language: "Odia / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #87 (Demo Reference)",
      preservation_urgency: "high",
      sources: [
        { title: "Odisha Lalit Kala Akademi Archive", type: "State Art Institution", is_demo: true }
      ],
      claims: [
        {
          id: "c-pt-1",
          claim_text: "Hand-incised on cured palm leaves using traditional iron stylus and soot rub.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Raghurajpur Crafts Guild Master Roster",
          is_demo_reference: true,
        },
        {
          id: "c-pt-2",
          claim_text: "Recognized under Geographical Indications Registry (Demo Reference #87).",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #87)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-05T09:00:00.000Z",
      updated_at: "2026-09-10T14:00:00.000Z",
    },
    created_at: "2026-09-05T09:00:00.000Z",
    updated_at: "2026-09-10T14:00:00.000Z",
  },

  // 8. Kashmiri Papier-Mâché
  {
    id: "prod-kashmiri-08",
    artisan_id: "artisan-ghulam-nabi",
    title: "Kashmiri Papier-Mâché Floral Trinket Box with Pure Gold Leaf",
    title_hi: "कश्मीरी पेपर-मैशी हस्तनिर्मित आभूषण मंजूषा (स्वर्ण पत्र युक्त)",
    description: "Hand-molded paper pulp decorative box cured with rice paste, smoothened with kashmiri stone, and painted with miniature Gul-o-Bulbul floral motifs and authentic 24k gold leaf lining.",
    description_hi: "शहतूत के पेड़ की छाल और कागज़ की लुगदी से बनी कश्मीरी डिबिया, जिस पर पारंपरिक गुल-ए-बुलबुल और 24 कैरेट स्वर्ण पत्ती से बारीक चित्रकारी की गई है।",
    category: "woodwork",
    craft_name: "Kashmiri Papier-Mâché",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    materials: ["Macerated Waste Paper", "Rice Starch Paste", "Aged Stone Polish", "24k Gold Leaf", "Natural Lacquer"],
    motifs: ["Gul-o-Bulbul (Rose and Nightingale)", "Chinar Leaf", "Almond Paisley (Badam)"],
    dimensions: { length: 14, width: 10, height: 7, unit: "cm" },
    inventory: 4,
    suggested_min_price: 2100,
    suggested_max_price: 2800,
    final_price: 2450,
    pricing_breakdown: {
      material_cost: 520,
      labor_hours: 14,
      craft_complexity: "High",
      hourly_benchmark: 135,
      fair_wage_subtotal: 1890,
      suggested_min_price: 2100,
      suggested_max_price: 2800,
      ondc_export_markup_suggestion: 3200,
      benchmark_source: "Jammu & Kashmir Directorate of Handicrafts Benchmark",
      rationale: "Material Cost ₹520 (Paper pulp + 24k gold leaf foil) + Estimated Labour (14 hrs fine brush miniature art @ ₹135/hr benchmark = ₹1,890). Suggested range ₹2,100 – ₹2,800. Final price decided by artisan.",
    },
    status: "published",
    featured_image_url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    additional_images: [],
    gi_status: "gi_registered",
    gi_demo_reference: "GI Application Ref #103 (Demo Reference)",
    gi_tag_applicable: true,
    gi_registry_number: null,
    gi_candidacy_status: "registered_verified",
    odop_product_tag: "Kashmir Papier-Mâché Art",
    artisan_story: "My family in Zadibal, Srinagar has carried this craft since Mir Sayyid Ali Hamadani brought Central Asian master craftsmen to the Kashmir Valley in the 14th century.",
    is_demo_data: true,
    ai_understanding: {
      craft_name: "Kashmiri Papier-Mâché",
      region: "Srinagar, Jammu & Kashmir",
      detected_materials: ["Macerated paper pulp", "24k gold leaf", "Natural varnish"],
      detected_motifs: ["Chinar leaf silhouette", "Gul-o-Bulbul miniature florals", "Gilded border ribbons"],
      language_detected: "Kashmiri / Urdu / Hindi",
      confidence_score: 0.95,
      speech_keywords: ["पेपर मैशी", "कश्मीर", "श्रीनगर", "गुल ए बुलबुल", "सोना", "चिनार"],
      visual_features: ["Molded paper matrix base", "Lacquered smooth finish", "Gold foil illumination"],
      safety_check_passed: true,
      gi_candidacy_note: "Registered Geographical Indication in Kashmir (Demo Reference #103)",
    },
    heritage_record: {
      id: "hr-kashmiri-08",
      product_id: "prod-kashmiri-08",
      craft_name: "Kashmiri Papier-Mâché",
      region: "Zadibal, Srinagar",
      state: "Jammu & Kashmir",
      district: "Srinagar",
      artisan_name: "Ghulam Nabi & Family",
      artisan_lineage: "Zadibal Papier-Mâché Ustad Tradition (5th Generation)",
      traditional_technique: "Sakhtsazi (molding macerated paper pulp and rice starch into shape) followed by Naqqashi (freehand painting with cat-hair brushes using mineral pigments and gold leaf lacquer).",
      materials: ["Pulp", "Rice Paste", "Gold Foil", "Mineral Oxides"],
      motifs: ["Chinar Leaf", "Gul-o-Bulbul", "Hazara Patterns"],
      cultural_story: "Introduced in the 14th century during the Sultanate period. The craft symbolizes the cross-pollination of Persian aesthetics and Kashmiri floral landscape.",
      artisan_story: "We burnish the molded surface with agate stone until it feels like ivory before painting with brushes made from domestic cat hair.",
      original_language: "Kashmiri / Urdu / Hindi",
      gi_status: "gi_registered",
      gi_demo_reference: "GI Application Ref #103 (Demo Reference)",
      preservation_urgency: "high",
      sources: [
        { title: "J&K Directorate of Handicrafts Heritage Registry", type: "State Archive", is_demo: true }
      ],
      claims: [
        {
          id: "c-km-1",
          claim_text: "Authentic two-stage Sakhtsazi and Naqqashi hand-molding and painting.",
          source_type: "artisan",
          provenance_label: "Artisan Provided",
          verification_status: "verified",
          source_reference: "Artisan studio validation and material verification",
          is_demo_reference: true,
        },
        {
          id: "c-km-2",
          claim_text: "GI Registered Handicraft of Jammu & Kashmir (Demo Reference #103).",
          source_type: "official",
          provenance_label: "Verified Source",
          verification_status: "verified",
          source_reference: "GI Registry India (Demo Reference #103)",
          is_demo_reference: true,
        }
      ],
      created_at: "2026-09-06T11:00:00.000Z",
      updated_at: "2026-09-10T16:30:00.000Z",
    },
    created_at: "2026-09-06T11:00:00.000Z",
    updated_at: "2026-09-10T16:30:00.000Z",
  },
];
